=== FinalForEach/Cosmic-Reach-Localization/assets/lang/lang.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/FinalForEach/Cosmic-Reach-Localization/tree/master/assets/lang/lang.schema.json",
    "title": "Cosmic Reach language",
    "description": "FinalForEach's Cosmic Reach game localization language schema",
    "type": "object",
    "additionalProperties": false,
    "__HOW_TO_ADD_PROPERTY__": "First, copy-paste a previous property ({type: 'string'} etc.), then change its key. Then update the minProperties field below to match the total count of the defined properties. (e.g. add 1 if you add 1 text etc.)",
    "minProperties": 114,
    "properties": {
        "metadata": {
            "type": "object",
            "description": "Special metadata property for the language",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string",
                    "description": "The language's name shown in the language menu"
                }
            },
            "required": [
                "name"
            ]
        },
        "startButton": {
            "type": "string"
        },
        "loadButton": {
            "type": "string"
        },
        "optionsButton": {
            "type": "string"
        },
        "quitButton": {
            "type": "string"
        },
        "vSyncButton": {
            "type": "string"
        },
        "creditsButton": {
            "type": "string"
        },
        "renderDistSlider": {
            "type": "string"
        },
        "invertedMouseButton": {
            "type": "string"
        },
        "mouseSensitivitySlider": {
            "type": "string"
        },
        "soundButton": {
            "type": "string"
        },
        "fovSlider": {
            "type": "string"
        },
        "maxFPS": {
            "type": "string"
        },
        "maxFPSUnlimited": {
            "type": "string"
        },
        "debugCrashButton": {
            "type": "string"
        },
        "keybindsButton": {
            "type": "string"
        },
        "languagesButton": {
            "type": "string"
        },
        "rendererButton": {
            "type": "string"
        },
        "rendererNaive": {
            "type": "string"
        },
        "rendererBatched": {
            "type": "string"
        },
        "doneButton": {
            "type": "string"
        },
        "preAlphaText": {
            "type": "string"
        },
        "okButton": {
            "type": "string"
        },
        "Lighting": {
            "type": "string"
        },
        "Respawn": {
            "type": "string"
        },
        "Return_To_Game": {
            "type": "string"
        },
        "Return_To_Menu": {
            "type": "string"
        },
        "Saving": {
            "type": "string"
        },
        "Dynamic_Sky": {
            "type": "string"
        },
        "Space_Day": {
            "type": "string"
        },
        "Dark_Night": {
            "type": "string"
        },
        "Earth_Day": {
            "type": "string"
        },
        "Orange_Sky": {
            "type": "string"
        },
        "Pitch_Dark": {
            "type": "string"
        },
        "Overcast": {
            "type": "string"
        },
        "Forward": {
            "type": "string"
        },
        "Backward": {
            "type": "string"
        },
        "Left": {
            "type": "string"
        },
        "Right": {
            "type": "string"
        },
        "Jump": {
            "type": "string"
        },
        "Crouch": {
            "type": "string"
        },
        "Sprint": {
            "type": "string"
        },
        "Prone": {
            "type": "string"
        },
        "Inventory": {
            "type": "string"
        },
        "Drop_Item": {
            "type": "string"
        },
        "Hide_UI": {
            "type": "string"
        },
        "Screenshot": {
            "type": "string"
        },
        "Debug_Info": {
            "type": "string"
        },
        "Attack_Break": {
            "type": "string"
        },
        "Pick_Block": {
            "type": "string"
        },
        "Use_Place": {
            "type": "string"
        },
        "No_Clip": {
            "type": "string"
        },
        "Reload_Shaders": {
            "type": "string"
        },
        "Fullscreen": {
            "type": "string"
        },
        "Create_New_World": {
            "type": "string"
        },
        "worldNameButton": {
            "type": "string"
        },
        "defaultWorldName": {
            "type": "string"
        },
        "worldSeedLabel": {
            "type": "string"
        },
        "worldSeedLabel2": {
            "type": "string"
        },
        "worldType": {
            "type": "string"
        },
        "Return_to_Main_Menu": {
            "type": "string"
        },
        "returnButton": {
            "type": "string"
        },
        "Open_Worlds_Directory": {
            "type": "string"
        },
        "YT_Channel": {
            "type": "string"
        },
        "Game_version": {
            "type": "string"
        },
        "MAC_warning": {
            "type": "string"
        },
        "Controller": {
            "type": "string"
        },
        "Controllers": {
            "type": "string"
        },
        "Controller_info": {
            "type": "string"
        },
        "on_state": {
            "type": "string"
        },
        "off_state": {
            "type": "string"
        },
        "World_name": {
            "type": "string"
        },
        "Screenshot_info": {
            "type": "string"
        },
        "Screenshot_error": {
            "type": "string"
        },
        "Loading": {
            "type": "string"
        },
        "mouseLeftButton": {
            "type": "string"
        },
        "mouseMiddleButton": {
            "type": "string"
        },
        "mouseRightButton": {
            "type": "string"
        },
        "mouseBackButton": {
            "type": "string"
        },
        "mouseForwardButton": {
            "type": "string"
        },
        "RuntimeException": {
            "type": "string"
        },
        "Tip1": {
            "type": "string"
        },
        "Tip2": {
            "type": "string"
        },
        "Tip3": {
            "type": "string"
        },
        "Tip4": {
            "type": "string"
        },
        "Tip5": {
            "type": "string"
        },
        "Tip6": {
            "type": "string"
        },
        "Tip7": {
            "type": "string"
        },
        "Tip8": {
            "type": "string"
        },
        "Tip9": {
            "type": "string"
        },
        "Tip10": {
            "type": "string"
        },
        "Tip11": {
            "type": "string"
        },
        "Tip12": {
            "type": "string"
        },
        "Tip13": {
            "type": "string"
        },
        "Tip14": {
            "type": "string"
        },
        "Tip15": {
            "type": "string"
        },
        "Tip16": {
            "type": "string"
        },
        "Tip17": {
            "type": "string"
        },
        "Tip18": {
            "type": "string"
        },
        "Tip19": {
            "type": "string"
        },
        "Tip20": {
            "type": "string"
        },
        "Tip21": {
            "type": "string"
        },
        "Tip22": {
            "type": "string"
        },
        "OddTip1": {
            "type": "string"
        },
        "OddTip2": {
            "type": "string"
        },
        "OddTip3": {
            "type": "string"
        },
        "OddTip4": {
            "type": "string"
        },
        "OddTip5": {
            "type": "string"
        },
        "OddTip6": {
            "type": "string"
        },
        "OddTip7": {
            "type": "string"
        },
        "OddTip8": {
            "type": "string"
        },
        "OddTip9": {
            "type": "string"
        },
        "OddTip10": {
            "type": "string"
        },
        "OddTip11": {
            "type": "string"
        }
    }
}

=== FinalForEach/Cosmic-Reach-Localization/assets/lang/lv_lv.json
{
    "metadata":
    {
      "name": "Latviešu"
    },
    "startButton": "Sākt",
    "loadButton": "Apskatīt saglabātās spēles",
    "optionsButton": "Opcijas",
    "quitButton": "Iziet",
    "vSyncButton": "Vsync: ",
    "renderDistSlider": "Redzes attālums: ",
    "invertedMouseButton": "Apgriezta pele: ",
    "mouseSensitivitySlider": "Peles jutīgums: ",
    "soundButton": "Skaņa: ",
    "fovSlider": "Redzes lauks: ",
    "maxFPS": "Max FPS: ",
    "maxFPSUnlimited": "Max FPS: Neierobežots",
    "debugCrashButton": "Atkļūdošana: Uzkārt spēli",
    "keybindsButton": "Tastatūra",
    "languagesButton": "Valoda",
    "doneButton": "Pabeigt",
    "preAlphaText": "Sveicināti Cosmic Reach! \n Šī spēle ir agrīnā tapšanas stadijā, tai ir trūkstoši satura elementi, tā nav tuvu pabeigtai, \n un jūs visticamāk saskarsieties ar kļūmēm un kļūdaini saglabātām pasaulēm.\n Viss var tikt mainīts patreizējā spēle neataino gala stadiju.\n Spēle ir pieejama, lai jūs varētu dot atsauksmes un palīdzēt noteikt spēles nākotni.\n Laimīgu testēšanu... un spēles laušanu!",
    "okButton": "Ok",
    "Lighting": "Apgaismojums: ",
    "Respawn": "Atdzīvoties",
    "Return_To_Game": "Atgriezties spēlē",
    "Return_To_Menu": "Atgriezties uz izvēlni",
    "Saving": "Saglabā...",
    "Space_Day": "Kosmosa diena",
    "Dark_Night": "Kosmosa nakts",
    "Earth_Day": "Zemes diena",
    "Orange_Sky": "Oranžas debesis",
    "Pitch_Dark": "Piķa tumsa",
    "Overcast": "Apmācies",
    "Forward": "Uz priekšu",
    "Backward": "Uz atpakaļu",
    "Left": "Pa kreisi",
    "Right": "Pa labi",
    "Jump": "Palēkties",
    "Crouch": "Pietupties",
    "Sprint": "Skriet",
    "Prone": "Gulties",
    "Inventory": "Soma",
    "Drop_Item": "Nomest priekšmetu",
    "Hide_UI": "Paslēpt lietotāja interfeisu",
    "Screenshot": "Ekrānšāviņš",
    "Debug_Info": "Atkļūdošanas informācija",
    "No_Clip": "No-Clip",
    "Reload_Shaders": "Pārlādēt ēnotājus (Shaders)",
    "Fullscreen": "Pilnekrāna režīms",
    "Create_New_World": "Izveidot jaunu pasauli",
    "worldNameButton": "Pasaules nosaukums: ",
    "defaultWorldName": "Jauna pasaule",
    "worldSeedLabel": "Pasaules ģenerēšanas atslēga: <Nejauša>",
    "worldSeedLabel2": "Pasaules ģenerēšanas atslēga: ",
    "worldType": "Pasaules tips: ",
    "Return_to_Main_Menu": "Atgriezties uz galveno izvēlni",
    "returnButton": "Atpakaļ",
    "Open_Worlds_Directory": "Atvērt pasauļu sarakstu",
    "YT_Channel": "Sekojiet līdzi spēles tapšanai - youtube.com/@finalforeach",
    "Game_version": "Cosmic Reach Versija Pre-alpha-",
    "MAC_warning": "UZMANĪBU: Mac sistēmas pašlaik netiek atbalstītas. Spēle visticamāk nestrādās.",
    "Controller": "Kontrolieris",
    "Controllers": "Kontrolieri",
    "Controller_info": " atrasts!\nKontrolieru atbalsts nav pilnvērtīgs,\nun tiks uzlabots nākamojos jauninājumos.",
    "on_state": "Ieslēgts",
    "off_state": "Izslēgts",
    "World_name": "Pasaule-",
    "Screenshot_info": "Ekrānšāviņš saglabāts ",
    "Screenshot_error": "Kļūme saglabājot ekrānšāviņu.",
    "Loading": "Notiek ielāde",
    "RuntimeException": "Neizdevās ielādēt pasauli: ",
    "Tip1": "Izloka līknes...",
    "Tip2": "Izkantē stūrus...",
    "Tip3": "Ieveido pasauli...",
    "Tip4": "Iekrāso gaismekļus...",
    "Tip5": "Skalda skaldņus...",
    "Tip6": "Pavairo blokus...",
    "Tip7": "Izkārto apgabalus...",
    "Tip8": "Uzkrāj kosmosa putekļus...",
    "Tip9": "Sarindo kubus...",
    "Tip10": "Apvieno apgabalus...",
    "Tip11": "Pieaudzē mēnesi...",
    "Tip12": "Sakārto somas...",
    "Tip13": "Fresnel-ificē...",
    "Tip14": "Kolonizē planētas...",
    "Tip15": "Knifs: Izvēlies bloku ar vidējo peles pogu!",
    "Tip16": "Knifs: Izmēģini citas apgaismošanas metodes pauzes izvēlnē!",
    "Tip17": "Knifs: Nospied '$keybind_hideUI' lai paslēptu lietotāja interfeisu",
    "Tip18": "Knifs: Nospied '$keybind_screenshot' lai uzņemtu ekrānšāviņu!",
    "Tip19": "Knifs: Nospied '$keybind_debugInfo' lai apskatītu atkļūdošanas informāciju",
    "Tip20": "Knifs: Nospied '$keybind_dropItem' to drop the current item!",
    "Tip21": "Knifs: Nospied '$keybind_openInventory' to open the inventory!",
    "Tip22": "Knifs: Ieskrienies pret sienu priekš 'sien-driļļa', lai tiktu tālāk nekā lecot.",
    "OddTip1": "Potē šūnas...",
    "OddTip2": "Inkubē...",
    "OddTip3": "Upurē izmēģinājuma trusīšus...",
    "OddTip4": "Skaita aitas...",
    "OddTip5": "Utilizē satrupējušos audus...",
    "OddTip6": "Ievāc cilmes šūnas...",
    "OddTip7": "Ievāc orgānu \"donorus\"...",
    "OddTip8": "Pēta leviatānu...",
    "OddTip9": "Atkārto piegājienus...",
    "OddTip10": "Kategorizē īpatņus...",
    "OddTip11": "Knifs: Entropijai nepretosies."
  }

=== FinalForEach/Cosmic-Reach-Localization/assets/lang/id_id.json
{
  "metadata":
  {
    "name": "Bahasa Indonesia"
  },
  "startButton": "Mulai",
  "loadButton": "Buka Direktori Penyimpanan",
  "optionsButton": "Opsi",
  "quitButton": "Keluar",
  "vSyncButton": "Vsync: ",
  "creditsButton": "Kredit",
  "renderDistSlider": "Jarak Render: ",
  "invertedMouseButton": "Mouse Terbalik: ",
  "mouseSensitivitySlider": "Sensitivitas Mouse: ",
  "soundButton": "Suara: ",
  "fovSlider": "FOV: ",
  "maxFPS": "FPS Maks: ",
  "maxFPSUnlimited": "FPS Maks: Tak terbatas",
  "debugCrashButton": "Debug: Crash permainan",
  "keybindsButton": "Keybinds",
  "languagesButton": "Bahasa",
  "rendererButton": "Renderer: ",
  "rendererNaive": "Naive",
  "rendererBatched": "Batched",
  "doneButton": "Selesai",
  "preAlphaText": "Selamat datang di Cosmic Reach! \n Game ini sedang dalam tahap awal pengembangan, fiturnya belum lengkap, belum mendekati selesai, \n dan kemungkinan besar akan terdapat bug, glitch, crash, dan korupsi dunia.\n Semuanya dapat berubah dan tidak mewakili permainan final.\n Ini tersedia untuk Kamu mainkan sehingga Kamu dapat memberikan umpan balik untuk membantu memandu masa depan game ini \n Selamat menguji... dan merusakan permainan!",
  "okButton": "Ok",
  "Lighting": "Pencahayaan: ",
  "Respawn": "Bangkit kembali",
  "Return_To_Game": "Kembali ke permainan",
  "Return_To_Menu": "Kembali ke menu",
  "Saving": "Menyimpan...",
  "Space_Day": "Siang Luar Angkasa",
  "Dark_Night": "Malam gelap",
  "Earth_Day": "Siang Bumi",
  "Orange_Sky": "Langit Oranye",
  "Pitch_Dark": "Gelap gulita",
  "Overcast": "Mendung",
  "Forward": "Maju",
  "Backward": "Mundur",
  "Left": "Kiri",
  "Right": "Kanan",
  "Jump": "Lompat",
  "Crouch": "Mendekam",
  "Sprint": "Lari",
  "Prone": "Tengkurap",
  "Inventory": "Inventaris",
  "Drop_Item": "Jatuhkan Item",
  "Hide_UI": "Sembunyikan UI",
  "Screenshot": "Tangkapan layar",
  "Debug_Info": "Info Debug",
  "No_Clip": "No-Clip",
  "Reload_Shaders": "Muat ulang Shaders",
  "Fullscreen": "Layar penuh",
  "Create_New_World": "Buat Dunia Baru",
  "worldNameButton": "Nama dunia: ",
  "defaultWorldName": "Dunia baru",
  "worldSeedLabel": "Benih dunia: <Acak>",
  "worldSeedLabel2": "Benih dunia: ",
  "worldType": "Tipe Dunia: ",
  "Return_to_Main_Menu": "Kembali ke Menu Utama",
  "returnButton": "Kembali",
  "Open_Worlds_Directory": "Buka Direktori Dunia",
  "YT_Channel": "Tonton devlognya di youtube.com/@finalforeach",
  "Game_version": "Cosmic Reach Versi Pre-alpha-",
  "MAC_warning": "PERINGATAN: Mac tidak didukung saat ini. Kemungkinan besar permainan ini tidak akan berjalan dengan benar.",
  "Controller": "Kontroler",
  "Controllers": "Kontroler",
  "Controller_info": " terdeteksi!\nDukungan kontroler belum lengkap saat ini,\ndan akan ditingkatkan di pembaruan selanjutnya.",
  "on_state": "Nyala",
  "off_state": "Mati",
  "World_name": "Dunia-",
  "Screenshot_info": "Tangkapan layar disimpan ke ",
  "Screenshot_error": "Terjadi kesalahan saat menyimpan tangkapan layar.",
  "Loading": "Memuat",
  "RuntimeException": "Tidak dapat memuat dunia: ",
  "Tip1": "Retikulasi spline...",
  "Tip2": "Menekan simpul...",
  "Tip3": "Membentuk dunia...",
  "Tip4": "Mewarnai cahaya...",
  "Tip5": "Membelah dua lempengan...",
  "Tip6": "Mengisi blok...",
  "Tip7": "Melapisi potongan...",
  "Tip8": "Mengumpulkan debu luar angkasa...",
  "Tip9": "Mengorbit kubus...",
  "Tip10": "Mengelompokkan potongan...",
  "Tip11": "Mengentalkan bulan...",
  "Tip12": "Membersihkan inventaris...",
  "Tip13": "Fresnel-fikasi...",
  "Tip14": "Menjajah planet...",
  "Tip15": "Tip: Pilih blok menggunakan tombol tengah mouse!",
  "Tip16": "Tip: Coba ubah mode pencahayaan yang berbeda di menu jeda!",
  "Tip17": "Tip: Tekan '$keybind_hideUI' untuk menyembunyikan antarmuka pengguna",
  "Tip18": "Tip: Tekan '$keybind_screenshot' untuk mengambil tangkapan layar!",
  "Tip19": "Tip: Tekan '$keybind_debugInfo' untuk melihat informasi debug",
  "Tip20": "Tip: Tekan '$keybind_dropItem' untuk menjatuhkan item saat ini!",
  "Tip21": "Tip: Tekan '$keybind_openInventory' untuk membuka inventaris!",
  "Tip22": "Tip: Berlari ke dinding untuk 'berlari di dinding', melangkah lebih jauh dari yang Kamu lakukan hanya dengan melompat.",
  "OddTip1": "Mencangkok sel...",
  "OddTip2": "Inkubasi...",
  "OddTip3": "Mengorbankan subjek...",
  "OddTip4": "Menghitung domba...",
  "OddTip5": "Membuang jaringan mati...",
  "OddTip6": "Memanen sel induk...",
  "OddTip7": "Mengumpulkan \"sumbangan\" organ...",
  "OddTip8": "Mengamati tricephalous...",
  "OddTip9": "Uji coba berulang kali...",
  "OddTip10": "Mengkategorikan spesimen...",
  "OddTip11": "Tip: Kamu tidak bisa melawan entropi."
}

=== FinalForEach/Cosmic-Reach-Localization/assets/lang/cy_gb.json
{
  "metadata":
  {
    "name": "Cymraeg"
  },
  "startButton": "Dechrau",
  "loadButton": "Agor Ffolder Gemau",
  "optionsButton": "Opsiynau",
  "quitButton": "Gadael",
  "vSyncButton": "Vsync: ",
  "renderDistSlider": "Pellter Rendro: ",
  "invertedMouseButton": "Gwrth-droi Llygoden: ",
  "mouseSensitivitySlider": "Sensitifrwydd Llygoden: ",
  "soundButton": "Swn: ",
  "fovSlider": "Maes Golwg: ",
  "maxFPS": "Max FPS: ",
  "maxFPSUnlimited": "Max FPS: Anghyfyngedig",
  "debugCrashButton": "Dadfygio: Chwalu y gêm",
  "keybindsButton": "Rhwymiadau Bysell",
  "languagesButton": "Iaith",
  "doneButton": "Gorffen",
  "preAlphaText": "Croeso i Cosmic Reach! \n Mae'r gêm yn datblygiad cynnar iawn, mae'n nodweddion coll, yn unman bron yn gyflawn, \n a bydd namau, problemau, chwalu a llygredd yn namau.\n Gall popeth newid ac dydy hwn ddim yn cynrychiolydd o'r gêm olaf.\n Mae'r gêm ar glawr i chwarae i chi roi adborth i arwain dyfodol y gêm \n Profi happus!... a tori-gêm!",
  "okButton": "Iawn",
  "Lighting": "llucheden: ",
  "Respawn": "Atgyfodi",
  "Return_To_Game": "Dychwelyd i'r gêm",
  "Return_To_Menu": "Dychwelyd i'r dewislen",
  "Saving": "Yn cadw...",
  "Space_Day": "Dydd Gofod",
  "Dark_Night": "Nos Tywyll",
  "Earth_Day": "Dydd Daear",
  "Orange_Sky": "Awyr Oren",
  "Pitch_Dark": "Hollol Dywyll",
  "Overcast": "Cymylog",
  "Forward": "Ymlaen",
  "Backward": "Yn ôl",
  "Left": "Chwith",
  "Right": "De",
  "Jump": "Neidio",
  "Crouch": "Swatio",
  "Sprint": "Rhedeg",
  "Prone": "Cropian",
  "Inventory": "Rhestr Eiddo",
  "Drop_Item": "Gollwng Eitem",
  "Hide_UI": "Cwato UI",
  "Screenshot": "Sgrinlun",
  "Debug_Info": "Gwybodaeth Dadfygio",
  "No_Clip": "Dim-clipio",
  "Reload_Shaders": "Ail-lwytho Arlliw-wyr",
  "Fullscreen": "Sgrîn Lawn",
  "Create_New_World": "Creu Byd Newydd",
  "worldNameButton": "Enw byd: ",
  "defaultWorldName": "Byd newydd",
  "worldSeedLabel": "Hedyn byd: <Random>",
  "worldSeedLabel2": "Hedyn byd: ",
  "worldType": "Teip byd: ",
  "Return_to_Main_Menu": "Dychwelyd i'r Dewislen",
  "returnButton": "Yn ôl",
  "Open_Worlds_Directory": "Agor Ffolder Gemau",
  "YT_Channel": "Gwilio'r devlogs ar youtube.com/@finalforeach",
  "Game_version": "Cosmic Reach Fersiwn Pre-alpha-",
  "MAC_warning": "RHYBUDD: Dydy Mac ddim yn gweithio ar hyn o bryd. Mae'r gêm yn annhebygol i weithio.",
  "Controller": "Rheolwr",
  "Controllers": "Rheolwyr",
  "Controller_info": " canfod!\nMae cymorth Rheolwr yn anghyflawn rwan,\nac cail amgen nes ymlaen.",
  "on_state": "Ymlaen",
  "off_state": "Oddi ar",
  "World_name": "Byd-",
  "Screenshot_info": "Cadw Sgrinlun i ",
  "Screenshot_error": "Problem Cadw Sgrinlun.",
  "Loading": "Llwytho",
  "RuntimeException": "Methu llwytho byd: ",
  "Tip1": "Tynnu'n ôl y splines...",
  "Tip2": "Fertigau gwasgu...",
  "Tip3": "Siapio'r byd...",
  "Tip4": "Goleuadau lliwio...",
  "Tip5": "Slabiau haneru...",
  "Tip6": "Poblogi blociau...",
  "Tip7": "Darnau haenu...",
  "Tip8": "Llwch gofod yn cronni...",
  "Tip9": "Ciwbiau cylchdroi...",
  "Tip10": "Yn sypynnu talpiau...",
  "Tip11": "Curdling y lleuad...",
  "Tip12": "Dad-annibendod rhestrau eiddo...",
  "Tip13": "Fresnel-ffugio...",
  "Tip14": "Gwladychu planedau...",
  "Tip15": "Awgrym: Pick block using y middle mouse button!",
  "Tip16": "Awgrym: Trïo newid y dull goleuo gwahanol yn y saib dewislen!",
  "Tip17": "Awgrym: Gwasgu '$keybind_hideUI' i cuddio'r user interface",
  "Tip18": "Awgrym: Gwasgu '$keybind_screenshot' i tynnu sgrinlun!",
  "Tip19": "Awgrym: Gwasgu '$keybind_debugInfo' i weld gwybodaethl dadfygio",
  "Tip20": "Awgrym: Gwasgu '$keybind_dropItem' i taflu eitem!",
  "Tip21": "Awgrym: Gwasgu '$keybind_openInventory' i agor y rhestr eiddo!",
  "Tip22": "Awgrym: Rhedeg yn erbyn wal i 'wall run', mynd pellach yna byddech chi neidio.",
  "OddTip1": "Grefftio celloedd...",
  "OddTip2": "Deori...",
  "OddTip3": "Aberthu pynciau...",
  "OddTip4": "Cyfrif defaid...",
  "OddTip5": "Gwaredu meinwe ymadawedig...",
  "OddTip6": "Cynaeafu bôn-gelloedd...",
  "OddTip7": "Casglu \"rhoddion\" organau...",
  "OddTip8": "Arsylwi tricephalous...",
  "OddTip9": "Treialon ailadroddus...",
  "OddTip10": "Categoreiddio sbesimenau...",
  "OddTip11": "Awgrym: Ni allwch ymladd yn erbyn entropi."
}

=== FinalForEach/Cosmic-Reach-Localization/assets/lang/gr_gl.json
{
    "metadata":
    {
      "name": "Kalaallisut (Greenlandic)"
    },
    "startButton": "Aallartigit",
    "loadButton": "Ammaruk Toqqornikoq Mappi",
    "optionsButton": "Toqqagassat",
    "quitButton": "Anillagit",
    "vSyncButton": "vSync: ",
    "renderDistSlider": "Isigisap Ugasissusaa: ",
    "invertedMouseButton": "Killormoortoq Muusi: ",
    "mouseSensitivitySlider": "Muusip Malussarissusia: ",
    "soundButton": "Nipia: ",
    "fovSlider": "FOV: ",
    "maxFPS": "Annerpaaffissaa FPS: ",
    "maxFPSUnlimited": "Annerpaaffissaq FPS: Killeqanngitsoq",
    "debugCrashButton": "Kukkusaq: Spilleq ajutooruk",
    "keybindsButton": "Naqitassamut Naqitassat",
    "languagesButton": "Oqaatsit",
    "doneButton": "Piareerpunga",
    "preAlphaText": "Tikilluarit Cosmic Reachimut! \n Spilleq suli sananeqarpoq, amigaateqarpoq atortunik, suli piareerneqanngilaq, \n aamma ajortoqarsinnaassooq, kukkusaqassooq, ajutoorneq aamma nunarsuaq ajortittoorneq.\n Suna tamaat allanngorsinnavoq aamma takutitsisuunngilaq spilleq piariikkamut.\n Spilliluumisinnaavutit malugititsinerussagavit ikiuutaallutit spillip siunissaanut \n Misiliilluarina... aamma spilleq-ajortinnera!",
    "okButton": "Ok",
    "Lighting": "Qila Qaamanera: ",
    "Respawn": "Uummaqqigit",
    "Return_To_Game": "Uterit Spillimut",
    "Return_To_Menu": "Uterit Menumut",
    "Saving": "Toqqorpaa...",
    "Space_Day": "Silaannarsuaq Ulloq",
    "Dark_Night": "Taartoq Unnuaq",
    "Earth_Day": "Nunarsuarmi Ulloq",
    "Orange_Sky": "Sungaartoq Aappaluttoq Qilak",
    "Pitch_Dark": "Taartuinnaq",
    "Overcast": "Nuiasoq",
    "Forward": "Siumut",
    "Backward": "Utimut",
    "Left": "Saamimmut",
    "Right": "Talerpimmut",
    "Jump": "Pissigit",
    "Crouch": "Ammoorit",
    "Sprint": "Arpagit",
    "Prone": "Pallorit",
    "Inventory": "Pigisat",
    "Drop_Item": "Nakkartiguk Atortoq",
    "Hide_UI": "Toqqoruk UI",
    "Screenshot": "Assiliigit",
    "Debug_Info": "Kukkusaq Paasissutissaa",
    "No_Clip": "Suunngitsunngorit",
    "Reload_Shaders": "Aallaqqaataaneeruk Qaamaneri",
    "Fullscreen": "Ulikkaaruk Sk√¶rm",
    "Create_New_World": "Nunarsualiorit",
    "worldNameButton": "Nunarsualiap Atia: ",
    "defaultWorldName": "Nutaaq Nunarsualiaq",
    "worldSeedLabel": "Nunarsualiap kisitsisia: <Arlaat>",
    "worldSeedLabel2": "Nunarsualiap kisitsisia: ",
    "worldType": "Nunarsualiaq Qanorittoq: ",
    "Return_to_Main_Menu": "Uterit Menu Pingaarnermut",
    "returnButton": "Uterit",
    "Open_Worlds_Directory": "Ammaruk Nunarsualiat Mappi",
    "YT_Channel": "Isiginnaaruk Spilleq sananeqarnera (Tuluttoorpoq/Englesk) youtube.com/@finalforeach",
    "Game_version": "Cosmic Reach Version Pre-alpha-",
    "MAC_warning": "MIANERSOQQUSSUUT: Macimut suli massakkut atorneqarsinnaanngilaq. Spilleq immaqa ajorsinnaavoq.",
    "Controller": "Aquttagaq",
    "Controllers": "Aquttakkat",
    "Controller_info": " nassaarineqarpoq!\n Aquttagamut Atortarnissaq suli piariinngilaq,\n aamma aaqqinneqassaaq siunissami spillimi.",
    "on_state": "Ikippunga",
    "off_state": "Qamippunga",
    "World_name": "Nunarsualiaq-",
    "Screenshot_info": "Toqqorpoq Assiliat uunga  ",
    "Screenshot_error": "Ajutoorpoq toqqornera assiliat.",
    "Loading": "Piariilerpoq",
    "RuntimeException": "Ajutoortoqarpoq nunarsualiornut isernissaa: ",
    "Tip1": "Ikiuut 1 Nutsersinnaangilara Uaniittoraluaq...",
    "Tip2": "Ikiuut 2 Nutsersinnaanngittoorpara aamma una...",
    "Tip3": "Isikkuliorpaa Nunarsualiat...",
    "Tip4": "Qalipaneqarput qaamanerit...",
    "Tip5": "Avinneqarput saluttut...",
    "Tip6": "Sananeqarpoq Issoqqaariffaarissut...",
    "Tip7": "Sanavai chunkit...",
    "Tip8": "Silaannarsuup pujoralai sanavai...",
    "Tip9": "Kaavippai Issoqqaariffaarissut...",
    "Tip10": "Sinneri chuckit sanavai...",
    "Tip11": "Qaammat!",
    "Tip12": "Piiarpai imaluunnit sanvai pisatat...",
    "Tip13": "Nunaliorluni Sivisua?...",
    "Tip14": "Nunarsiartarivai Planetit...",
    "Tip15": "Ikiuut: Muusimi kaavittaga toorukku kippariffissaaq isigisat tigussuat!",
    "Tip16": "Ikiuut: allanngortiguk qilak menup qulaaniittoq toorlugu!",
    "Tip17": "Ikiuut: tooruk F1 taava suna tamaat tammassoq kisia nunaq minillugu",
    "Tip18": "Ikiuut: tooruk F2 assiliiniaruit spilliminngaanniit!",
    "Tip19": "Ikiuut: Tooruk F3 paasissutissat takuniaukkit kisia Nunaliarnut iseqqaassuutit",
    "Tip20": "Ikiuut: Tooruk Q paarisat peerniarukku!",
    "Tip21": "Ikiuut: Tooruk E atortut takuniarukkit!",
    "Tip22": "Ikiuut: Iikkamut arpagit taava 'iigakkut arpassaatit', ungasinnerumukarsinnaassatit pissittaarnatit.",
    "OddTip1": "Eqqumiittut ikiuut 1: Paarnaarussiviliorit...",
    "OddTip2": "Eqqumiittut ikiuut 2: Manniliorit...",
    "OddTip3": "Eqqumiittut ikiuut 3: Tuniorakkit misissugat...",
    "OddTip4": "Eqqumiittut ikiuut 4: Kisikkit savatit...",
    "OddTip5": "Eqqumiittut ikiuut 5: Soqutiginagit toqunikut cellit...",
    "OddTip6": "Eqqumiittut ikiuut 6: Tigoorakkit celliliortartut...",
    "OddTip7": "Eqqumiittut ikiuut 7: Tigoorakkit timip atortui soorlu puat il. il.\"tuniorakkat\"...",
    "OddTip8": "Eqqumiittut ikiuut 8: Isiginnaaruk tricephalous...",
    "OddTip9": "Eqqumiittut ikiuut 9: Misileqattaaruk assiganik iluatsinnissaata tugaanut...",
    "OddTip10": "Eqqumiittut ikiuut 10: Immikkuukkit misissukkatit...",
    "OddTip11": "Eqqumiittut ikiuut 11: Unammisinnanngilat sanaat."
  }
