=== FinalForEach/Cosmic-Reach-Localization/assets/lang/lang.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/FinalForEach/Cosmic-Reach-Localization/tree/master/assets/lang/lang.schema.json",
    "title": "Cosmic Reach language",
    "description": "FinalForEach's Cosmic Reach game localization language schema",
    "type": "object",
    "additionalProperties": false,
    "__HOW_TO_ADD_PROPERTY__": "First, copy-paste a previous property ({type: 'string'} etc.), then change its key. Then update the minProperties field below to match the total count of the defined properties. (e.g. add 1 if you add 1 text etc.)",
    "minProperties": 114,
    "properties": {
        "metadata": {
            "type": "object",
            "description": "Special metadata property for the language",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string",
                    "description": "The language's name shown in the language menu"
                }
            },
            "required": [
                "name"
            ]
        },
        "startButton": {
            "type": "string"
        },
        "loadButton": {
            "type": "string"
        },
        "optionsButton": {
            "type": "string"
        },
        "quitButton": {
            "type": "string"
        },
        "vSyncButton": {
            "type": "string"
        },
        "creditsButton": {
            "type": "string"
        },
        "renderDistSlider": {
            "type": "string"
        },
        "invertedMouseButton": {
            "type": "string"
        },
        "mouseSensitivitySlider": {
            "type": "string"
        },
        "soundButton": {
            "type": "string"
        },
        "fovSlider": {
            "type": "string"
        },
        "maxFPS": {
            "type": "string"
        },
        "maxFPSUnlimited": {
            "type": "string"
        },
        "debugCrashButton": {
            "type": "string"
        },
        "keybindsButton": {
            "type": "string"
        },
        "languagesButton": {
            "type": "string"
        },
        "rendererButton": {
            "type": "string"
        },
        "rendererNaive": {
            "type": "string"
        },
        "rendererBatched": {
            "type": "string"
        },
        "doneButton": {
            "type": "string"
        },
        "preAlphaText": {
            "type": "string"
        },
        "okButton": {
            "type": "string"
        },
        "Lighting": {
            "type": "string"
        },
        "Respawn": {
            "type": "string"
        },
        "Return_To_Game": {
            "type": "string"
        },
        "Return_To_Menu": {
            "type": "string"
        },
        "Saving": {
            "type": "string"
        },
        "Dynamic_Sky": {
            "type": "string"
        },
        "Space_Day": {
            "type": "string"
        },
        "Dark_Night": {
            "type": "string"
        },
        "Earth_Day": {
            "type": "string"
        },
        "Orange_Sky": {
            "type": "string"
        },
        "Pitch_Dark": {
            "type": "string"
        },
        "Overcast": {
            "type": "string"
        },
        "Forward": {
            "type": "string"
        },
        "Backward": {
            "type": "string"
        },
        "Left": {
            "type": "string"
        },
        "Right": {
            "type": "string"
        },
        "Jump": {
            "type": "string"
        },
        "Crouch": {
            "type": "string"
        },
        "Sprint": {
            "type": "string"
        },
        "Prone": {
            "type": "string"
        },
        "Inventory": {
            "type": "string"
        },
        "Drop_Item": {
            "type": "string"
        },
        "Hide_UI": {
            "type": "string"
        },
        "Screenshot": {
            "type": "string"
        },
        "Debug_Info": {
            "type": "string"
        },
        "Attack_Break": {
            "type": "string"
        },
        "Pick_Block": {
            "type": "string"
        },
        "Use_Place": {
            "type": "string"
        },
        "No_Clip": {
            "type": "string"
        },
        "Reload_Shaders": {
            "type": "string"
        },
        "Fullscreen": {
            "type": "string"
        },
        "Create_New_World": {
            "type": "string"
        },
        "worldNameButton": {
            "type": "string"
        },
        "defaultWorldName": {
            "type": "string"
        },
        "worldSeedLabel": {
            "type": "string"
        },
        "worldSeedLabel2": {
            "type": "string"
        },
        "worldType": {
            "type": "string"
        },
        "Return_to_Main_Menu": {
            "type": "string"
        },
        "returnButton": {
            "type": "string"
        },
        "Open_Worlds_Directory": {
            "type": "string"
        },
        "YT_Channel": {
            "type": "string"
        },
        "Game_version": {
            "type": "string"
        },
        "MAC_warning": {
            "type": "string"
        },
        "Controller": {
            "type": "string"
        },
        "Controllers": {
            "type": "string"
        },
        "Controller_info": {
            "type": "string"
        },
        "on_state": {
            "type": "string"
        },
        "off_state": {
            "type": "string"
        },
        "World_name": {
            "type": "string"
        },
        "Screenshot_info": {
            "type": "string"
        },
        "Screenshot_error": {
            "type": "string"
        },
        "Loading": {
            "type": "string"
        },
        "mouseLeftButton": {
            "type": "string"
        },
        "mouseMiddleButton": {
            "type": "string"
        },
        "mouseRightButton": {
            "type": "string"
        },
        "mouseBackButton": {
            "type": "string"
        },
        "mouseForwardButton": {
            "type": "string"
        },
        "RuntimeException": {
            "type": "string"
        },
        "Tip1": {
            "type": "string"
        },
        "Tip2": {
            "type": "string"
        },
        "Tip3": {
            "type": "string"
        },
        "Tip4": {
            "type": "string"
        },
        "Tip5": {
            "type": "string"
        },
        "Tip6": {
            "type": "string"
        },
        "Tip7": {
            "type": "string"
        },
        "Tip8": {
            "type": "string"
        },
        "Tip9": {
            "type": "string"
        },
        "Tip10": {
            "type": "string"
        },
        "Tip11": {
            "type": "string"
        },
        "Tip12": {
            "type": "string"
        },
        "Tip13": {
            "type": "string"
        },
        "Tip14": {
            "type": "string"
        },
        "Tip15": {
            "type": "string"
        },
        "Tip16": {
            "type": "string"
        },
        "Tip17": {
            "type": "string"
        },
        "Tip18": {
            "type": "string"
        },
        "Tip19": {
            "type": "string"
        },
        "Tip20": {
            "type": "string"
        },
        "Tip21": {
            "type": "string"
        },
        "Tip22": {
            "type": "string"
        },
        "OddTip1": {
            "type": "string"
        },
        "OddTip2": {
            "type": "string"
        },
        "OddTip3": {
            "type": "string"
        },
        "OddTip4": {
            "type": "string"
        },
        "OddTip5": {
            "type": "string"
        },
        "OddTip6": {
            "type": "string"
        },
        "OddTip7": {
            "type": "string"
        },
        "OddTip8": {
            "type": "string"
        },
        "OddTip9": {
            "type": "string"
        },
        "OddTip10": {
            "type": "string"
        },
        "OddTip11": {
            "type": "string"
        }
    }
}

=== FinalForEach/Cosmic-Reach-Localization/assets/lang/fi_fi.json
{
  "metadata":
  {
    "name": "suomi"
  },
  "startButton": "Aloita",
  "loadButton": "Avaa Tallennuskansio",
  "optionsButton": "Asetukset",
  "quitButton": "Poistu",
  "vSyncButton": "Vsync: ",
  "renderDistSlider": "Renderöintietäisyys: ",
  "invertedMouseButton": "Käänteinen Hiiri: ",
  "mouseSensitivitySlider": "Hiiren Herkkyys: ",
  "soundButton": "Äänet: ",
  "fovSlider": "Näkökenttä: ",
  "maxFPS": "Max FPS: ",
  "maxFPSUnlimited": "Max FPS: Rajaton",
  "debugCrashButton": "Debug: Kaada Peli",
  "keybindsButton": "Näppäimet",
  "languagesButton": "Kieli",
  "doneButton": "Valmis",
  "preAlphaText": "Tervetuloa Cosmic Reachiin! \n Pelin kehitys on vasta alkumetreillä sekä kaukana valmiista. Pelistä puuttuu ominaisuuksia.\n Tulet luultavasti kohtaamaan bugeja, glitchejä, kaatumisia sekä maailmakorruptiota.\n Kaikki on muutoksenvaraista, eikä nykyinen tila edusta valmista peliä.\n Peli on pelattavissa, jotta voit antaa palautetta ja auttaa ohjaamaan pelin tulevaisuutta. \n Hauskaa kokeilua... sekä pelinrikkomista!",
  "okButton": "Ok",
  "Lighting": "Valaisu: ",
  "Respawn": "Synny Uudelleen",
  "Return_To_Game": "Palaa Peliin",
  "Return_To_Menu": "Palaa Valikkoon",
  "Saving": "Tallennetaan...",
  "Space_Day": "Avaruuspäivä",
  "Dark_Night": "Pimeä Yö",
  "Earth_Day": "Maan päivä",
  "Orange_Sky": "Oranssi Taivas",
  "Pitch_Dark": "Pilkkopimeä",
  "Overcast": "Pilvinen",
  "Forward": "Eteen",
  "Backward": "Taakse",
  "Left": "Vasen",
  "Right": "Oikea",
  "Jump": "Hyppy",
  "Crouch": "Kyykky",
  "Sprint": "Juoksu",
  "Prone": "Makuu",
  "Inventory": "Tavaraluettelo",
  "Drop_Item": "Pudota Esine",
  "Hide_UI": "Piilota Käyttöliittymä",
  "Screenshot": "Kuvakaappaus",
  "Debug_Info": "Debugtiedot",
  "No_Clip": "No-Clip",
  "Reload_Shaders": "Uudelleenlataa Shaderit",
  "Fullscreen": "Kokonäyttötila",
  "Create_New_World": "Luo Uusi Maailma",
  "worldNameButton": "Maailman nimi: ",
  "defaultWorldName": "Uusi Maailma",
  "worldSeedLabel": "Maailman siemen: <Random>",
  "worldSeedLabel2": "Maailman siemen: ",
  "worldType": "Maailman tyyppi: ",
  "Return_to_Main_Menu": "Palaa Päävalikkoon",
  "returnButton": "Takaisin",
  "Open_Worlds_Directory": "Avaa Maailmakansio",
  "YT_Channel": "Katso kehityslogeja osoitteesta youtube.com/@finalforeach",
  "Game_version": "Cosmic Reach Versio Pre-alpha-",
  "MAC_warning": "VAROITUS: Mac ei ole tuettu alusta tällä hetkellä. Peli ei luultavasti toimi.",
  "Controller": "Ohjain",
  "Controllers": "Ohjaimet",
  "Controller_info": " tunnistettu!\nOhjaintuki on keskeneräinen,\nja sitä tullaan tulevaisuudessa parantamaan päivityksillä.",
  "on_state": "Päällä",
  "off_state": "Pois",
  "World_name": "Maailma-",
  "Screenshot_info": "Kuvakaappaus tallennettu: ",
  "Screenshot_error": "Virhe tallentaessa kuvakaappausta.",
  "Loading": "Ladataan",
  "RuntimeException": "Maailman lataus epäonnistui: ",
  "Tip1": "Paistetaan pikseleitä...",
  "Tip2": "Puristellaan verteksejä...",
  "Tip3": "Muotoillaan maailmaa...",
  "Tip4": "Värjäillään valoja...",
  "Tip5": "Puolitetaan laattoja...",
  "Tip6": "Lasketaan kuution kulmia...",
  "Tip7": "Kerrostetaan lohkoja...",
  "Tip8": "Kerätään avaruuspölyä...",
  "Tip9": "Taivutetaan kuutioita...",
  "Tip10": "Porrastetaan lohkoja...",
  "Tip11": "Tyhjennetään täysikuuta...",
  "Tip12": "Järjestellään tavaraluetteloita...",
  "Tip13": "Valaistaan kuun pimeää puolta...",
  "Tip14": "Kolonisoidaan planeettoja...",
  "Tip15": "Vihja: Poimi palikka hiiren keskinäppäimellä!",
  "Tip16": "Vihje: Kokeile eri valaistusasetuksia taukovalikossa!",
  "Tip17": "Vihje: Paina '$keybind_hideUI' piilottaaksesi käyttöliittymän!",
  "Tip18": "Vihje: Paina '$keybind_screenshot' ottaaksesi kuvakaappauksen!",
  "Tip19": "Vihje: Paina '$keybind_debugInfo' katsoaksesi debug-tietoja!",
  "Tip20": "Vihje: Paina '$keybind_dropItem' pudottaaksesi valitun esineen!",
  "Tip21": "Vihje: Paina '$keybind_openInventory' avataksesi tavaraluettelon!",
  "Tip22": "Vihje: Tee 'wall run' juoksemalla seinää pitkin päästäksesi hyppäämistä pidemmälle.",
  "OddTip1": "Siirretään soluja...",
  "OddTip2": "Haudotaan...",
  "OddTip3": "Suoritetaan uhrauksia...",
  "OddTip4": "Lasketaan lampaita...",
  "OddTip5": "Hävitetään kuollutta kudosta...",
  "OddTip6": "Kerätään kantasoluja...",
  "OddTip7": "Kerätään \"elinluovutuksia\"...",
  "OddTip8": "Tarkkailaan tricephalousta...",
  "OddTip9": "Toistetaan kokeita...",
  "OddTip10": "Luokitellaan näytteitä...",
  "OddTip11": "Vihje: entropiaa vastaan kamppailu on turhaa."
}

=== FinalForEach/Cosmic-Reach-Localization/assets/lang/sv_se.json
{
    "metadata":
    {
      "name": "Svenska"
    },
    "startButton": "Starta",
    "loadButton": "Öppna Sparfils Mappen",
    "optionsButton": "Inställningar",
    "quitButton": "Avsluta",
    "vSyncButton": "Vsync: ",
    "renderDistSlider": "Render Distance: ",
    "invertedMouseButton": "Invertad Mus: ",
    "mouseSensitivitySlider": "Mus Känslighet: ",
    "soundButton": "Ljud: ",
    "fovSlider": "FOV: ",
    "maxFPS": "Max FPS: ",
    "maxFPSUnlimited": "Max FPS: Oändlig",
    "debugCrashButton": "Debug: Krascha Spelet",
    "keybindsButton": "Tangentbindningar",
    "languagesButton": "Språk",
    "doneButton": "Klar",
    "preAlphaText": "Välkommen till Cosmic Reach! \n Spelet är i ett väldigt tidigt stadie, funktioner saknas, det är inte i närheten av klart, \n det kommer troligtvis att finnas buggar, glitcher, crascher and världs korruption.\n Allting kan komma att ändras och är inte representativt för det färdiga spelet.\n Det är tillgängligt för dig att spela så att du kan ge feedback och hjälpa till att styra framtiden av spelet \n Glad testning... och spelkraschning",
    "okButton": "Ok",
    "Lighting": "Ljus: ",
    "Respawn": "Återuppstå",
    "Return_To_Game": "Tillbaka till spelet",
    "Return_To_Menu": "Tillbaka till menyn",
    "Saving": "Sparar...",
    "Space_Day": "Rymden Dag",
    "Dark_Night": "Mörk Natt",
    "Earth_Day": "Jorden Dag",
    "Orange_Sky": "Orange Himmel",
    "Pitch_Dark": "Bäcksvart",
    "Overcast": "Mulet",
    "Forward": "Framåt",
    "Backward": "Bakåt",
    "Left": "Vänster",
    "Right": "Höger",
    "Jump": "Hoppa",
    "Crouch": "Huka",
    "Sprint": "Springa",
    "Prone": "Krypa",
    "Inventory": "Förråd",
    "Drop_Item": "Kasta Föremål",
    "Hide_UI": "Göm UI",
    "Screenshot": "Skärmbild",
    "Debug_Info": "Debug Information",
    "No_Clip": "No-Clip",
    "Reload_Shaders": "Ladda om Shaders",
    "Fullscreen": "Fullskärm",
    "Create_New_World": "Skapa ny värld",
    "worldNameButton": "Världens namn: ",
    "defaultWorldName": "Ny Värld",
    "worldSeedLabel": "Världens frö: <Slumpmässig>",
    "worldSeedLabel2": "Världens frö: ",
    "worldType": "Världstyp: ",
    "Return_to_Main_Menu": "Återvänd till Huvudmeny",
    "returnButton": "Tillbaka",
    "Open_Worlds_Directory": "Öppna Världfils Mappen",
    "YT_Channel": "Se devlogarna på youtube.com/@finalforeach",
    "Game_version": "Cosmic Reach Version Pre-alpha-",
    "MAC_warning": "Varning: Mac stöds ej för tillfället. Spelet kommer troligtvis inte att fungera.",
    "Controller": "Kontroller",
    "Controllers": "Kontroller",
    "Controller_info": " upptäckt!\nStöd för kontroller är inte klart än,\noch kommer att förbättras i senare uppdateringar.",
    "on_state": "På",
    "off_state": "Av",
    "World_name": "Värld-",
    "Screenshot_info": "Sparade skärmbild vid ",
    "Screenshot_error": "Fel när skämbilden skulle sparas.",
    "Loading": "Laddar",
    "RuntimeException": "Kunde inte ladda värld: ",
    "Tip1": "Framställer kurvor...",
    "Tip2": "Krymper hörn...",
    "Tip3": "Formger världen...",
    "Tip4": "Färgar ljus...",
    "Tip5": "Skivar skivor...",
    "Tip6": "Populating blocks...",
    "Tip7": "Staplar chunks...",
    "Tip8": "Samlar rymddamm...",
    "Tip9": "Sätter kuber i omlopp...",
    "Tip10": "Batchar chunks...",
    "Tip11": "Ytsar månen...",
    "Tip12": "Vårstädar förråd...",
    "Tip13": "Fresnel-iserar...",
    "Tip14": "Koloniserar planeter...",
    "Tip15": "Tips: Välj block med mellersta musknappen!",
    "Tip16": "Tips: Testa att byta ljusläge i pausmenyn!",
    "Tip17": "Tips: Tryck på '$keybind_hideUI' för att gömma användargränssnittet",
    "Tip18": "Tips: Tryck på '$keybind_screenshot' för att ta en skärmbild!",
    "Tip19": "Tips: Tryck på '$keybind_debugInfo' för att se debug information",
    "Tip20": "Tips: Tryck på '$keybind_dropItem' för att kasta det hållna föremålet!",
    "Tip21": "Tips: Tryck på '$keybind_openInventory' för att öppna ditt förråd!",
    "Tip22": "Tips: Spring mot en vägg för att 'springa på väggen', då kommer du längre än om du bara hade hoppat.",
    "OddTip1": "Ympar celler...",
    "OddTip2": "Inkuberar...",
    "OddTip3": "Offrar subjekt...",
    "OddTip4": "Räknar får...",
    "OddTip5": "Kastar avliden vävnad...",
    "OddTip6": "Samlar in stamceller...",
    "OddTip7": "Samlar in organ \"donationer\"...",
    "OddTip8": "Observerar tricefalus...",
    "OddTip9": "Upprepar test...",
    "OddTip10": "Kategoriserar provexemplar...",
    "OddTip11": "Tips: Du kan inte kämpa mot entropi."
  }

=== FinalForEach/Cosmic-Reach-Localization/assets/lang/zh_tw.json
{
    "metadata":
    {
      "name": "正體中文（臺灣）"
    },
    "startButton": "開始遊戲",
    "loadButton": "開啟存檔目錄",
    "optionsButton": "選項",
    "quitButton": "退出",
    "vSyncButton": "垂直同步：",
    "renderDistSlider": "視野距離：",
    "invertedMouseButton": "滑鼠反轉：",
    "mouseSensitivitySlider": "滑鼠靈敏度：",
    "soundButton": "音效：",
    "fovSlider": "視野廣度：",
    "maxFPS": "最大幀率：",
    "maxFPSUnlimited": "最大幀率：無限制",
    "debugCrashButton": "偵錯：強制崩潰遊戲",
    "keybindsButton": "按鍵設定",
    "languagesButton": "語言",
    "doneButton": "完成",
    "preAlphaText": "歡迎來到Cosmic Reach！ \n 本遊戲仍處於早期開發階段，功能並不完備，亦無完整遊戲內容， \n 可能會出現漏洞、閃退或導致世界檔案損毀。 \n 一切內容皆可能發生改變並且不代表最終遊戲。 \n 歡迎試玩本遊戲以便您提供回饋、協助指引遊戲未來走向。 \n 盡情測試... 和搞破壞！",
    "okButton": "Ok",
    "Lighting": "亮度：",
    "Respawn": "重生",
    "Return_To_Game": "返回遊戲",
    "Return_To_Menu": "返回選單",
    "Saving": "存檔中...",
    "Space_Day": "太空日",
    "Dark_Night": "黑夜",
    "Earth_Day": "地球日",
    "Orange_Sky": "橙天",
    "Pitch_Dark": "漆黑",
    "Overcast": "陰天",
    "Forward": "前進",
    "Backward": "後退",
    "Left": "左",
    "Right": "右",
    "Jump": "跳躍",
    "Crouch": "蹲下",
    "Sprint": "衝刺",
    "Prone": "臥地",
    "Inventory": "背包",
    "Drop_Item": "丟棄物品",
    "Hide_UI": "隱藏介面",
    "Screenshot": "截圖",
    "Debug_Info": "偵錯資訊",
    "No_Clip": "穿牆",
    "Reload_Shaders": "重整光影",
    "Fullscreen": "全螢幕",
    "Create_New_World": "創建新世界",
    "worldNameButton": "世界名稱：",
    "defaultWorldName": "新世界",
    "worldSeedLabel": "世界種子碼：隨機",
    "worldSeedLabel2": "世界種子碼：",
    "worldType": "世界類型：",
    "Return_to_Main_Menu": "返回主選單",
    "returnButton": "返回",
    "Open_Worlds_Directory": "開啟世界資料夾",
    "YT_Channel": "查看開發日誌：youtube.com/@finalforeach",
    "Game_version": "Cosmic Reach 版本 Pre-alpha-",
    "MAC_warning": "警告：當前不支援Mac裝置。遊戲很可能無法運行。",
    "Controller": "遊戲控制器",
    "Controllers": "遊戲控制器",
    "Controller_info": " 成功偵測！\n控制器當前並不提供完整支援，\n將在往後更新中進行改善。",
    "on_state": "開",
    "off_state": "關",
    "World_name": "世界-",
    "Screenshot_info": "儲存截圖至 ",
    "Screenshot_error": "儲存截圖時發生錯誤。",
    "Loading": "載入中",
    "RuntimeException": "無法載入世界：",
    "Tip1": "編織樣條...",
    "Tip2": "壓縮頂點...",
    "Tip3": "形塑世界...",
    "Tip4": "上色光源...",
    "Tip5": "半磚切片...",
    "Tip6": "填充方塊...",
    "Tip7": "疊加區塊...",
    "Tip8": "匯聚星塵...",
    "Tip9": "方塊入軌...",
    "Tip10": "區塊分批...",
    "Tip11": "凝成月球...",
    "Tip12": "整理背包...",
    "Tip13": "菲涅耳化...",
    "Tip14": "殖民行星...",
    "Tip15": "提示：使用滑鼠中鍵快速選取方塊！",
    "Tip16": "提示：在暫停選單中試試不同的亮度模式！",
    "Tip17": "提示：按下 '$keybind_hideUI' 隱藏遊戲介面",
    "Tip18": "提示：按下 '$keybind_screenshot' 擷取遊戲畫面！",
    "Tip19": "提示：按下 '$keybind_debugInfo' 查看偵錯資訊",
    "Tip20": "提示：按下 '$keybind_dropItem' 丟棄手中物品！",
    "Tip21": "提示：按下 '$keybind_openInventory' 打開背包！",
    "Tip22": "提示：對牆衝刺使出「牆跑」，比一般跳躍來得更遠。",
    "OddTip1": "移植細胞...",
    "OddTip2": "孵化...",
    "OddTip3": "獻祭物品...",
    "OddTip4": "數羊...",
    "OddTip5": "清除凋亡組織...",
    "OddTip6": "收成幹細胞...",
    "OddTip7": "收集器官\"捐贈\"...",
    "OddTip8": "觀察三頭獸...",
    "OddTip9": "反覆試驗...",
    "OddTip10": "歸類標本...",
    "OddTip11": "提示：你不能違背熵。"
  }

=== FinalForEach/Cosmic-Reach-Localization/assets/lang/da_dk.json
{
    "metadata":
    {
      "name": "Dansk (Danmark)"
    },
    "startButton": "Start",
    "loadButton": "Åben Gemt Data (Stifinder)",
    "optionsButton": "Indstillinger",
    "quitButton": "Afslut Spil",
    "vSyncButton": "Vsync: ",
    "renderDistSlider": "Synslængde: ",
    "invertedMouseButton": "Spejlvend Mus: ",
    "mouseSensitivitySlider": "Musesensitivitet: ",
    "soundButton": "Lyd: ",
    "fovSlider": "Synsfelt: ",
    "maxFPS": "Maks. FPS: ",
    "maxFPSUnlimited": "Maks. FPS: Ubegrænset",
    "debugCrashButton": "Debug: Crash spillet",
    "keybindsButton": "Tastebindinger",
    "languagesButton": "Sprog",
    "doneButton": "Bekræft",
    "preAlphaText": "Velkommen til Cosmic Reach! \n Spillet er tidligt i sin udvikling, derfor er der features som ikke er udviklet endnu. \n Forvent bugs, glitches, crashes, verdenskorruption og alt muligt andet godt da spillet ikke er færdigt endnu. \n Alt i spillet lige nu kan ændre sig og repræsenterer ikke nødvendigvis det endelige produkt. \n Man kan spille spillet i en ikke færdig tilstand for, at *du* kan komme med feedback og have indflydelse på, hvordan spillet kommer til at være i fremtiden. \n God testning og spil-ødelæggelse!",
    "okButton": "Ok",
    "Lighting": "Beslysning: ",
    "Respawn": "Genopstå",
    "Return_To_Game": "Fortset Spil",
    "Return_To_Menu": "Gå til Menu",
    "Saving": "Gemmer...",
    "Space_Day": "Dag i Rummet",
    "Dark_Night": "Mørk Nat",
    "Earth_Day": "Dag på Jorden",
    "Orange_Sky": "Orange Himmel",
    "Pitch_Dark": "Kulsort",
    "Overcast": "Overskyet",
    "Forward": "Gå Fremad",
    "Backward": "Gå Baglæns",
    "Left": "Gå til Venstre",
    "Right": "Gå til Højre",
    "Jump": "Hop",
    "Crouch": "Snig",
    "Sprint": "Løb",
    "Prone": "Kravl",
    "Inventory": "Åben/luk Tasken",
    "Drop_Item": "Kast Genstand",
    "Hide_UI": "Gem UI",
    "Screenshot": "Skærmbillede",
    "Debug_Info": "Debug Information",
    "No_Clip": "No-Clip",
    "Reload_Shaders": "Genindlæs Shaders",
    "Fullscreen": "Fuldskærm",
    "Create_New_World": "Lav Ny Verden",
    "worldNameButton": "Verdens navn: ",
    "defaultWorldName": "Ny Verden",
    "worldSeedLabel": "Verdens seed: <Tilfældig>",
    "worldSeedLabel2": "Verden seed: ",
    "worldType": "Verden Type: ",
    "Return_to_Main_Menu": "Gå til Hovedmenuen",
    "returnButton": "Tilbage",
    "Open_Worlds_Directory": "Åben Verdens Data (Stifinder)",
    "YT_Channel": "Følg med i udviklen af spillet på youtube.com/@finalforeach",
    "Game_version": "Cosmic Reach Version Pre-alpha-",
    "MAC_warning": "Advarsel: Mac (Apple) er ikke understøttet på nuværende tidspunkt. Det er ikke sikkert at spille kan køre på Mac.",
    "Controller": "Controller",
    "Controllers": "Controllerere",
    "Controller_info": " fundet!\nController support are ikke fuldt understøttet endnu,\ncontrollerunderstøttelse vil blive forbedret i senere opdateringer.",
    "on_state": "Tændt",
    "off_state": "Slukket",
    "World_name": "Verden-",
    "Screenshot_info": "Gemmer Skærmbillede til ",
    "Screenshot_error": "Fejl under lagring af Skærmbilledet.",
    "Loading": "Indlæser",
    "RuntimeException": "Fejl under åbningen af verdnen: ",
    "Tip1": "Omstrukturer kurver...",
    "Tip2": "Minimere hjørner...",
    "Tip3": "Former verdnen...",
    "Tip4": "Farver lysene...",
    "Tip5": "Halverer fliserne...",
    "Tip6": "Placere blokene...",
    "Tip7": "Stabler chunksene...",
    "Tip8": "Samler rumstøvet...",
    "Tip9": "Sætter blokene i kredsløb...",
    "Tip10": "Smider chunksene i system...",
    "Tip11": "Oster månen...",
    "Tip12": "Ryder op på værelset...",
    "Tip13": "Fresnel-ificerer...",
    "Tip14": "Kolonialisere stjernerne...",
    "Tip15": "Tip: Hurtig vælg blok med miderste muse knap!",
    "Tip16": "Tip: Prøv de forskellige belysningsindstilligere direkte fra pausemenuen!",
    "Tip17": "Tip: Tryk '$keybind_hideUI' for at gemme spil brugergrænsefladen væk",
    "Tip18": "Tip: Tryk '$keybind_screenshot' for at tage et Skærmbillede!",
    "Tip19": "Tip: Tryk '$keybind_debugInfo' for at vise debugging information",
    "Tip20": "Tip: Tryk '$keybind_dropItem' for at smide gendstanden du holder på jorden!",
    "Tip21": "Tip: Tryk '$keybind_openInventory' for at åbne din taske!",
    "Tip22": "Tip: Hvis du løber op imod en væg så kan du løbe langs den meget længere end, hvis du kun hoppede.",
    "OddTip1": "Poder celler...",
    "OddTip2": "Inkuberer...",
    "OddTip3": "Ofre undersåttere...",
    "OddTip4": "Tæller får...",
    "OddTip5": "Forkaster ødelagt væv...",
    "OddTip6": "Høster stamceller...",
    "OddTip7": "Samler organ\"donationer\"...",
    "OddTip8": "Iagttager tricephalous...",
    "OddTip9": "Gentager tests...",
    "OddTip10": "Kategoriserer organismer...",
    "OddTip11": "Tip: Kampen mod entropi er ikke en som du kan vinde.."
  }
