=== FinalForEach/Cosmic-Reach-Localization/assets/lang/lang.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/FinalForEach/Cosmic-Reach-Localization/tree/master/assets/lang/lang.schema.json",
    "title": "Cosmic Reach language",
    "description": "FinalForEach's Cosmic Reach game localization language schema",
    "type": "object",
    "additionalProperties": false,
    "__HOW_TO_ADD_PROPERTY__": "First, copy-paste a previous property ({type: 'string'} etc.), then change its key. Then update the minProperties field below to match the total count of the defined properties. (e.g. add 1 if you add 1 text etc.)",
    "minProperties": 114,
    "properties": {
        "metadata": {
            "type": "object",
            "description": "Special metadata property for the language",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string",
                    "description": "The language's name shown in the language menu"
                }
            },
            "required": [
                "name"
            ]
        },
        "startButton": {
            "type": "string"
        },
        "loadButton": {
            "type": "string"
        },
        "optionsButton": {
            "type": "string"
        },
        "quitButton": {
            "type": "string"
        },
        "vSyncButton": {
            "type": "string"
        },
        "creditsButton": {
            "type": "string"
        },
        "renderDistSlider": {
            "type": "string"
        },
        "invertedMouseButton": {
            "type": "string"
        },
        "mouseSensitivitySlider": {
            "type": "string"
        },
        "soundButton": {
            "type": "string"
        },
        "fovSlider": {
            "type": "string"
        },
        "maxFPS": {
            "type": "string"
        },
        "maxFPSUnlimited": {
            "type": "string"
        },
        "debugCrashButton": {
            "type": "string"
        },
        "keybindsButton": {
            "type": "string"
        },
        "languagesButton": {
            "type": "string"
        },
        "rendererButton": {
            "type": "string"
        },
        "rendererNaive": {
            "type": "string"
        },
        "rendererBatched": {
            "type": "string"
        },
        "doneButton": {
            "type": "string"
        },
        "preAlphaText": {
            "type": "string"
        },
        "okButton": {
            "type": "string"
        },
        "Lighting": {
            "type": "string"
        },
        "Respawn": {
            "type": "string"
        },
        "Return_To_Game": {
            "type": "string"
        },
        "Return_To_Menu": {
            "type": "string"
        },
        "Saving": {
            "type": "string"
        },
        "Dynamic_Sky": {
            "type": "string"
        },
        "Space_Day": {
            "type": "string"
        },
        "Dark_Night": {
            "type": "string"
        },
        "Earth_Day": {
            "type": "string"
        },
        "Orange_Sky": {
            "type": "string"
        },
        "Pitch_Dark": {
            "type": "string"
        },
        "Overcast": {
            "type": "string"
        },
        "Forward": {
            "type": "string"
        },
        "Backward": {
            "type": "string"
        },
        "Left": {
            "type": "string"
        },
        "Right": {
            "type": "string"
        },
        "Jump": {
            "type": "string"
        },
        "Crouch": {
            "type": "string"
        },
        "Sprint": {
            "type": "string"
        },
        "Prone": {
            "type": "string"
        },
        "Inventory": {
            "type": "string"
        },
        "Drop_Item": {
            "type": "string"
        },
        "Hide_UI": {
            "type": "string"
        },
        "Screenshot": {
            "type": "string"
        },
        "Debug_Info": {
            "type": "string"
        },
        "Attack_Break": {
            "type": "string"
        },
        "Pick_Block": {
            "type": "string"
        },
        "Use_Place": {
            "type": "string"
        },
        "No_Clip": {
            "type": "string"
        },
        "Reload_Shaders": {
            "type": "string"
        },
        "Fullscreen": {
            "type": "string"
        },
        "Create_New_World": {
            "type": "string"
        },
        "worldNameButton": {
            "type": "string"
        },
        "defaultWorldName": {
            "type": "string"
        },
        "worldSeedLabel": {
            "type": "string"
        },
        "worldSeedLabel2": {
            "type": "string"
        },
        "worldType": {
            "type": "string"
        },
        "Return_to_Main_Menu": {
            "type": "string"
        },
        "returnButton": {
            "type": "string"
        },
        "Open_Worlds_Directory": {
            "type": "string"
        },
        "YT_Channel": {
            "type": "string"
        },
        "Game_version": {
            "type": "string"
        },
        "MAC_warning": {
            "type": "string"
        },
        "Controller": {
            "type": "string"
        },
        "Controllers": {
            "type": "string"
        },
        "Controller_info": {
            "type": "string"
        },
        "on_state": {
            "type": "string"
        },
        "off_state": {
            "type": "string"
        },
        "World_name": {
            "type": "string"
        },
        "Screenshot_info": {
            "type": "string"
        },
        "Screenshot_error": {
            "type": "string"
        },
        "Loading": {
            "type": "string"
        },
        "mouseLeftButton": {
            "type": "string"
        },
        "mouseMiddleButton": {
            "type": "string"
        },
        "mouseRightButton": {
            "type": "string"
        },
        "mouseBackButton": {
            "type": "string"
        },
        "mouseForwardButton": {
            "type": "string"
        },
        "RuntimeException": {
            "type": "string"
        },
        "Tip1": {
            "type": "string"
        },
        "Tip2": {
            "type": "string"
        },
        "Tip3": {
            "type": "string"
        },
        "Tip4": {
            "type": "string"
        },
        "Tip5": {
            "type": "string"
        },
        "Tip6": {
            "type": "string"
        },
        "Tip7": {
            "type": "string"
        },
        "Tip8": {
            "type": "string"
        },
        "Tip9": {
            "type": "string"
        },
        "Tip10": {
            "type": "string"
        },
        "Tip11": {
            "type": "string"
        },
        "Tip12": {
            "type": "string"
        },
        "Tip13": {
            "type": "string"
        },
        "Tip14": {
            "type": "string"
        },
        "Tip15": {
            "type": "string"
        },
        "Tip16": {
            "type": "string"
        },
        "Tip17": {
            "type": "string"
        },
        "Tip18": {
            "type": "string"
        },
        "Tip19": {
            "type": "string"
        },
        "Tip20": {
            "type": "string"
        },
        "Tip21": {
            "type": "string"
        },
        "Tip22": {
            "type": "string"
        },
        "OddTip1": {
            "type": "string"
        },
        "OddTip2": {
            "type": "string"
        },
        "OddTip3": {
            "type": "string"
        },
        "OddTip4": {
            "type": "string"
        },
        "OddTip5": {
            "type": "string"
        },
        "OddTip6": {
            "type": "string"
        },
        "OddTip7": {
            "type": "string"
        },
        "OddTip8": {
            "type": "string"
        },
        "OddTip9": {
            "type": "string"
        },
        "OddTip10": {
            "type": "string"
        },
        "OddTip11": {
            "type": "string"
        }
    }
}

=== FinalForEach/Cosmic-Reach-Localization/assets/lang/ca_ca.json
{
  "metadata":
  {
    "name": "Català"
  },
  "startButton": "Jugar",
  "loadButton": "Obre el directori de desades",
  "optionsButton": "Opcions",
  "quitButton": "Sortir",
  "vSyncButton": "Vsync: ",
  "renderDistSlider": "Distància de renderització: ",
  "invertedMouseButton": "Ratolí invertit: ",
  "mouseSensitivitySlider": "Sensibilitat del ratolí: ",
  "soundButton": "So: ",
  "fovSlider": "FOV: ",
  "maxFPS": "Màx. FPS: ",
  "maxFPSUnlimited": "Màx. FPS: Sense límit",
  "debugCrashButton": "Depurar: Fer fallar el joc",
  "keybindsButton": "Assignacions de tecles",
  "languagesButton": "Idioma",
  "doneButton": "Fet",
  "preAlphaText": "Benvingut a Cosmic Reach! \n El joc es troba en una fase molt inicial de desenvolupament, li falten funcionalitats, està lluny de ser complet, \n i probablement tindrà errors, defectes i corrupció de móns.\n Tot està subjecte a canvis i no és representatiu del joc final.\n Està disponible perquè puguis donar feedback per ajudar a guiar el futur d'aquest joc \n Bon proveït de proves... i a trencar el joc!",
  "okButton": "D'acord",
  "Lighting": "Il·luminació: ",
  "Respawn": "Ressuscitar",
  "Return_To_Game": "Tornar al joc",
  "Return_To_Menu": "Tornar al menú",
  "Saving": "Guardant...",
  "Space_Day": "Dia a l'Espai",
  "Dark_Night": "Nit fosca",
  "Earth_Day": "Dia a la Terra",
  "Orange_Sky": "Cel Taronja",
  "Pitch_Dark": "Foscor absoluta",
  "Overcast": "Ennuvolat",
  "Forward": "Endavant",
  "Backward": "Enrere",
  "Left": "Esquerra",
  "Right": "Dreta",
  "Jump": "Saltar",
  "Crouch": "Agatxar-se",
  "Sprint": "Córrer",
  "Prone": "Tombar-se",
  "Inventory": "Inventari",
  "Drop_Item": "Tirar l'Objecte",
  "Hide_UI": "Amagar la IU",
  "Screenshot": "Captura de Pantalla",
  "Debug_Info": "Informació de Depuració",
  "No_Clip": "No-Clip",
  "Reload_Shaders": "Recarregar Shaders",
  "Fullscreen": "Pantalla Completa",
  "Create_New_World": "Crear Nou Món",
  "worldNameButton": "Nom del món: ",
  "defaultWorldName": "Món Nou",
  "worldSeedLabel": "Llavor del Món: <Aleatori>",
  "worldSeedLabel2": "Llavor del Món: ",
  "worldType": "Tipus de món: ",
  "Return_to_Main_Menu": "Tornar al Menú Principal",
  "returnButton": "Enrere",
  "Open_Worlds_Directory": "Obre el Directori de Móns",
  "YT_Channel": "Mira els devlogs a youtube.com/@finalforeach",
  "Game_version": "Versió de Cosmic Reach Pre-alfa-",
  "MAC_warning": "ADVERTÈNCIA: El Mac no està suportat en aquest moment. És poc probable que el joc funcioni.",
  "Controller": "Controlador",
  "Controllers": "Controladors",
  "Controller_info": " detectat!\nEl suport del controlador està incomplet ara,\n i s'incrementarà en actualitzacions posteriors.",
  "on_state": "Activat",
  "off_state": "Desactivat",
  "World_name": "Món-",
  "Screenshot_info": "Captura guardada a ",
  "Loading": "Carregant",
  "RuntimeException": "No es pot carregar el món: ",
  "Tip1": "Reticulant splines...",
  "Tip2": "Esmolant vèrtexs...",
  "Tip3": "Donant forma al món...",
  "Tip4": "Donant color a les llums...",
  "Tip5": "Partint les lloses...",
  "Tip6": "Poblant blocs...",
  "Tip7": "Estratificant chunks...",
  "Tip8": "Acumulant pols espacial...",
  "Tip9": "Orbitant cubs...",
  "Tip10": "Agrupant chunks...",
  "Tip11": "Coagulant la lluna...",
  "Tip12": "Desordenant inventaris...",
  "Tip13": "Fresnel-ificant...",
  "Tip14": "Colonitzant planetes...",
  "Tip15": "Consell: Selecciona un bloc amb la rodeta del ratolí!",
  "Tip16": "Consell: Prova a canviar els diferents modes d'il·luminació al menú de pausa!",
  "Tip17": "Consell: Prem '$keybind_hideUI' per amagar la interfície d'usuari",
  "Tip18": "Consell: Prem '$keybind_screenshot' per fer una captura de pantalla!",
  "Tip19": "Consell: Prem '$keybind_debugInfo' per veure informació de depuració",
  "Tip20": "Consell: Prem '$keybind_dropItem' per deixar l'objecte actual!",
  "Tip21": "Consell: Prem '$keybind_openInventory' per obrir l'inventari!",
  "Tip22": "Consell: Corre contra una paret per 'correr pel mur', anant més lluny que si només saltessis.",
  "OddTip1": "Engraftant cèl·lules...",
  "OddTip2": "Incubant...",
  "OddTip3": "Sacrificant subjectes...",
  "OddTip4": "Comptant ovelles...",
  "OddTip5": "Descartant teixits morts...",
  "OddTip6": "Cultivant cèl·lules mare...",
  "OddTip7": "Recollint 'donacions' d'òrgans...",
  "OddTip8": "Observant tricephalous...",
  "OddTip9": "Repetint proves...",
  "OddTip10": "Categoritzant espècimens...",
  "OddTip11": "Consell: No pots lluitar en contra de l'entropia."
}

=== FinalForEach/Cosmic-Reach-Localization/assets/lang/sr_sp.json
{
    "metadata":
    {
      "name": "Српски"
    },
    "startButton": "Започни",
    "loadButton": "Отвори сачуване светове",
    "optionsButton": "Подешавања",
    "quitButton": "Изађи из игре",
    "vSyncButton": "Vsync: ",
    "renderDistSlider": "Видљивост: ",
    "invertedMouseButton": "Изврни миш: ",
    "mouseSensitivitySlider": "Осетљивост миша: ",
    "soundButton": "Звук: ",
    "fovSlider": "Видно поље: ",
    "maxFPS": "Максимални FPS: ",
    "maxFPSUnlimited": "Максимални FPS: Неограничен",
    "debugCrashButton": "Дебаг: Крешуј игру",
    "keybindsButton": "Поставке тастера",
    "languagesButton": "Језик",
    "doneButton": "Готово",
    "preAlphaText": "Добродошли у Cosmic Reach! \n Игра је у веома раној фази развоја, фале јој карактеристике, није ни близу завршетка \n и вероватно ће имати багове, гличеве, крешовање и корупцију света.\n Све се може променити и није репрезентација завршене игре.\n Игра је доступна како би сте дали повратне информације и обликовали будућност ове игре \n Срећно тестирање... и рушење игре!",
    "okButton": "У реду",
    "Lighting": "Осветљење: ",
    "Respawn": "Реинкарнација",
    "Return_To_Game": "Врати се у игру",
    "Return_To_Menu": "Врати се на мени",
    "Saving": "Чување...",
    "Space_Day": "Свермирски дан",
    "Dark_Night": "Тамна ноћ",
    "Earth_Day": "Земаљски дан",
    "Orange_Sky": "Наранџасто небо",
    "Pitch_Dark": "Мркли мрак",
    "Overcast": "Облачно",
    "Forward": "Напред",
    "Backward": "Назад",
    "Left": "Лево",
    "Right": "Десно",
    "Jump": "Скок",
    "Crouch": "Чучање",
    "Sprint": "Трчање",
    "Prone": "Лежање",
    "Inventory": "Инвентар",
    "Drop_Item": "Баци изабрани предмет",
    "Hide_UI": "Сакриј интерфејс",
    "Screenshot": "Усликај",
    "Debug_Info": "Дебаг информације",
    "No_Clip": "No-Clip",
    "Reload_Shaders": "Поново учитај Shader-e",
    "Fullscreen": "Цео екран",
    "Create_New_World": "Направи нови свет",
    "worldNameButton": "Име света: ",
    "defaultWorldName": "Нови свет",
    "worldSeedLabel": "Семе света: <Насумично>",
    "worldSeedLabel2": "Семе света: ",
    "worldType": "Врста света: ",
    "Return_to_Main_Menu": "Врати се на главни мени",
    "returnButton": "Назад",
    "Open_Worlds_Directory": "Отвори фасциклу светова",
    "YT_Channel": "Одгледај девлог на youtube.com/@finalforeach",
    "Game_version": "Cosmic Reach верзија Pre-alpha-",
    "MAC_warning": "Упозорење: Mac тренутно није подржан. Игра вероватно неће радити.",
    "Controller": "Контролер",
    "Controllers": "Контролери",
    "Controller_info": " пронађен!\nКонтролери тренутно нису у потпуности подржани,\nи биће дорађени у следећим верзијама.",
    "on_state": "Укључено",
    "off_state": "Искључено",
    "World_name": "Свет-",
    "Screenshot_info": "Слика сачувана у ",
    "Screenshot_error": "Грешка при чувању слике.",
    "Loading": "Учитавање",
    "RuntimeException": "Грешка при учитавању света: ",
    "Tip1": "Ретикулирање кривих...",
    "Tip2": "Гњечење тачака...",
    "Tip3": "Обликовање света...",
    "Tip4": "Бојење светла...",
    "Tip5": "Сечење плоча...",
    "Tip6": "Насељавање блокова...",
    "Tip7": "Таложење чанкова...",
    "Tip8": "Таложење свемирске прашине...",
    "Tip9": "Орбитирање коцака...",
    "Tip10": "Спајање чанкова...",
    "Tip11": "Подсиривање месеца...",
    "Tip12": "Чишчење инвентара...",
    "Tip13": "Френелификација...",
    "Tip14": "Колонизирање планета...",
    "Tip15": "Савет: Одабери блок кликом на средње дугме на мишу!",
    "Tip16": "Tip: Савет: Покушај да промениш врсте осветљења у пауза мениjу!",
    "Tip17": "Савет: Притисни '$keybind_hideUI' да сакријеш интерфејс",
    "Tip18": "Савет: Притисни '$keybind_screenshot' да усликаш!",
    "Tip19": "Савет: Притисни '$keybind_debugInfo' да видиш дебаг информације",
    "Tip20": "Савет: Притисни '$keybind_dropItem' да бациш изабрани предмет!",
    "Tip21": "Савет: Притисни '$keybind_openInventory' да отвориш инвентар!",
    "Tip22": "Савет: Трчи у зид како би одрадио 'wall run', да би прескочио већу раздаљину.",
    "OddTip1": "Пресађивање ћелија...",
    "OddTip2": "Инкубирање...",
    "OddTip3": "Жртвовање поданика...",
    "OddTip4": "Бројање оваца...",
    "OddTip5": "Одбацивање мртвог ткива...",
    "OddTip6": "Прикупљање матичних ћелија...",
    "OddTip7": "Прикпуљање органских \"донација\"...",
    "OddTip8": "Гледање трикефалоса...",
    "OddTip9": "Понављање експеримената...",
    "OddTip10": "Категоризирање примерака...",
    "OddTip11": "Савет: Не можеш се борити против ентропије."
  }

=== FinalForEach/Cosmic-Reach-Localization/assets/lang/sk_sk.json
{
    "metadata":
    {
      "name": "Slovenčina (Slovensko)"
    },
    "startButton": "Štart",
    "loadButton": "Otvoriť Priečinok pre Ukladanie", 
    "optionsButton": "Nastavenia",
    "quitButton": "Ukončiť hru",
    "vSyncButton": "Vsync: ",
    "renderDistSlider": "Dohľadnosť: ",
    "invertedMouseButton": "Invertovať myš: ",
    "mouseSensitivitySlider": "Citlivosť myši: ",
    "soundButton": "Zvuk: ",
    "fovSlider": "Zorné pole: ",
    "maxFPS": "Max FPS: ",
    "maxFPSUnlimited": "Max FPS: Neobmedzené",
    "debugCrashButton": "Debug: Zhodiť hru",
    "keybindsButton": "Klávesové skratky",
    "languagesButton": "Jazyk",
    "doneButton": "Hotovo",
    "preAlphaText": "Vitaj v Cosmic Reach! \n Hra je ešte stále vo vývojovej fázy, chýbajú jej nejaké funkcie, je ďaleko od dokončenia, \n a pravdepodobne bude mať bugy, glitche, spadnutia a korupcie sveta.\n Všetko sa môže zmeniť a nereprezentuje finálny produkt.\n Je to sprístupnené pre vás na hranie aby ste mohli poskytnúť spätnú väzbu a tak pomôcť s budúcim vývojom tejto hry \n Šťastné testovanie... a ničenie hry!", 
    "okButton": "Ok",
    "Lighting": "Osvetlenie: ",
    "Respawn": "Oživiť",
    "Return_To_Game": "Späť do hry",
    "Return_To_Menu": "Návrat do menu",
    "Saving": "Ukladám...",
    "Space_Day": "Vesmírny Deň",
    "Dark_Night": "Temná Noc",
    "Earth_Day": "Zemný Deň",
    "Orange_Sky": "Oranžová Obloha",
    "Pitch_Dark": "Úplná Tma",
    "Overcast": "Zamračené",
    "Forward": "Dopredu",
    "Backward": "Dozadu",
    "Left": "Doľava",
    "Right": "Doprava",
    "Jump": "Vyskočiť",
    "Crouch": "Zakrádať sa",
    "Sprint": "Behať",
    "Prone": "Plaziť sa",
    "Inventory": "Inventár",
    "Drop_Item": "Odhodiť predmet",
    "Hide_UI": "Skryť UI",
    "Screenshot": "Snímka obrazovky",
    "Debug_Info": "Debug Informácie",
    "No_Clip": "No-Clip",
    "Reload_Shaders": "Obnoviť Tieňovače",
    "Fullscreen": "Celá obrazovka",
    "Create_New_World": "Vytvoriť Nový Svet",
    "worldNameButton": "Názov sveta: ",
    "defaultWorldName": "Nový svet",
    "worldSeedLabel": "Seed na vygenerovanie sveta: <Random>",
    "worldSeedLabel2": "Seed na vygenerovanie sveta: ",
    "worldType": "Typ Sveta: ",
    "Return_to_Main_Menu": "Zobraziť Menu",
    "returnButton": "Späť",
    "Open_Worlds_Directory": "Otvoriť Priečinok Svetov",
    "YT_Channel": "Sleduj vývoj na youtube.com/@finalforeach",
    "Game_version": "Cosmic Reach Verzia Pre-alpha-",
    "MAC_warning": "VAROVANIE: Mac nie je momentálne podporovaný. Je veľká šanca že hra nebude fungovať.",
    "Controller": "Ovládač",
    "Controllers": "Ovládače",
    "Controller_info": " detekované!\nPodpora ovládača je momentálne nekompletná,\na bude vylepšená v neskorších verziách.",
    "on_state": "On",
    "off_state": "Off",
    "World_name": "Svet-",
    "Screenshot_info": "Uložilo snímku obrazovky do ",
    "Screenshot_error": "Chyba pri ukladaní snímky obrazovky.",
    "Loading": "Načíťava",
    "RuntimeException": "Nemohlo načítať svet: ",
    "Tip1": "Reticulating splines...",
    "Tip2": "Squishing vertices...",
    "Tip3": "Shaping the world...",
    "Tip4": "Colouring lights...",
    "Tip5": "Halving slabs...",
    "Tip6": "Populating blocks...",
    "Tip7": "Layering chunks...",
    "Tip8": "Accumulating space dust...",
    "Tip9": "Orbiting cubes...",
    "Tip10": "Batching chunks...",
    "Tip11": "Curdling the moon...",
    "Tip12": "De-cluttering inventories...",
    "Tip13": "Fresnel-ificating...",
    "Tip14": "Colonizing planets...",
    "Tip15": "Tip: Vyber block pomocou stlačenia kolieska myši",
    "Tip16": "Tip: Skús zmeniť osvetlenie v esc menu!",
    "Tip17": "Tip: Stlač '$keybind_hideUI' na skrytie UI!",
    "Tip18": "Tip: Stlač '$keybind_screenshot' pre snímku obrazovky!",
    "Tip19": "Tip: Stlač '$keybind_debugInfo' pre debug informácie!",
    "Tip20": "Tip: Stlač '$keybind_dropItem' pre vyhodenie objektu!",
    "Tip21": "Tip: Stlač '$keybind_openInventory' pre otvorenie inventára!",
    "Tip22": "Tip: Rozbehni sa oproti stene pre 'wall run', dostaneš sa ďalej než sa dá len skákaním.",
    "OddTip1": "Grafting cells...",
    "OddTip2": "Incubating...",
    "OddTip3": "Sacrificing subjects...",
    "OddTip4": "Counting sheep...",
    "OddTip5": "Discarding deceased tissue...",
    "OddTip6": "Harvesting stem cells...",
    "OddTip7": "Collecting organ \"donations\"...",
    "OddTip8": "Observing tricephalous...",
    "OddTip9": "Repeating trials...",
    "OddTip10": "Categorizing specimens...",
    "OddTip11": "Tip: Nemôžeš bojovať proti entropii."
  }

=== FinalForEach/Cosmic-Reach-Localization/assets/lang/en_us_pig_latin.json
{
  "metadata":
  {
    "name": "Englishyay (igpay atinlay)"
  },
  "startButton": "Artstay",
  "loadButton": "Openyay Avesay Irectoriday",
  "optionsButton": "Optionsyay",
  "quitButton": "itquay",
  "vSyncButton": "yncvsay: ",
  "renderDistSlider": "Enderray Istanceday: ",
  "invertedMouseButton": "Invertedyay Ousemay: ",
  "mouseSensitivitySlider": "Ousemay Ensitivitysay: ",
  "soundButton": "Oundsay: ",
  "fovSlider": "FOV: ",
  "maxFPS": "Axmay FPS: ",
  "maxFPSUnlimited": "Axmay FPS: Unlimitedyay",
  "debugCrashButton": "Ebugday: Ashcray ethay amegay",
  "keybindsButton": "Eybindskay",
  "languagesButton": "Anguagelay",
  "doneButton": "oneday",
  "preAlphaText": "elcomeway otay osmiccay eachray! \n ethay amegay isyay inyay eryvay earlyyay evelopmentday , ityay isyay issingmay eaturesfay , isyay owherenay earnay ompletecay, \n andyay illway ikelylay avehay ugsbay , itchesglay , ashescray andyay orldway orruptioncay.\n everythingyay isyay ubjectsay otay angechay andyay isyay otnay epresentativeray ofyay ethay inalfay amegay.\n it'syay availableyay orfay ouyay otay ayplay osay atthay ouyay ancay ivegay eedbackfay otay elphay uidegay ethay uturefay ofyay isthay amegay \n appyhay estingtay .  .  . andyay ame-breakinggay!",
  "okButton": "Okyay",
  "Lighting": "ightinglay: ",
  "Respawn": "espawnray",
  "Return_To_Game": "eturnray otay amegay",
  "Return_To_Menu": "eturnray otay enumay",
  "Saving": "avingsay...",
  "Space_Day": "acespay ayday",
  "Dark_Night": "arkday ightnay",
  "Earth_Day": "Earthyay ayday",
  "Orange_Sky": "angeoray yskay",
  "Pitch_Dark": "itchpay arkday",
  "Overcast": "Overcastyay",
  "Forward": "orwardfay",
  "Backward": "ackwardbay",
  "Left": "eftlay",
  "Right": "ightray",
  "Jump": "umpjay",
  "Crouch": "ouchcray",
  "Sprint": "intspray",
  "Prone": "onepray",
  "Inventory": "Inventory-yay",
  "Drop_Item": "opdray Itemyay",
  "Hide_UI": "idehay UIyay",
  "Screenshot": "eenshotscray",
  "Debug_Info": "ebugday Infoyay",
  "No_Clip": "onay-ipclay",
  "Reload_Shaders": "eloadray adersshay",
  "Fullscreen": "ullscreenfay", 
  "Create_New_World": "eatecray ewnay orldway",
  "worldNameButton": "orldway amenay: ",
  "defaultWorldName": "ewnay orldway",
  "worldSeedLabel": "orldway eedsay: <andomray>",
  "worldSeedLabel2": "orldway eedsay: ",
  "worldType": "orldway ypetay: ",
  "Return_to_Main_Menu": "eturnray otay ainmay enumay",
  "returnButton": "ackbay",
  "Open_Worlds_Directory": "Openyay orldsway irectoryday",
  "YT_Channel": "atchway ethay evlogsday atyay youtube.com/@finalforeach",
  "Game_version": "osmiccay eachray ersionvay epray-alphayay-",
  "MAC_warning": "ARNINGWAY: acMay isyay otnay upportedsay atyay isthay imetay. ethay amegay isyay unlikelyay otay orkway.",
  "Controller": "ontrollercay",
  "Controllers": "ontrollerscay",
  "Controller_info": " etectedday!\nontrollercay upportsay isyay incompleteyay ownay,\nandyay illway ebay improvedyay inyay aterlay updatesyay.",
  "on_state": "Onyay",
  "off_state": "Offyay",
  "World_name": "orldway-",
  "Screenshot_info": "avedsay eenshotscray otay ",
  "Loading": "oadinglay",
  "RuntimeException": "ouldcay otnay oadlay orldway: ",
  "Tip1": "eticulatingray inessplay...",
  "Tip2": "ishingsquay erticesvay...",
  "Tip3": "apingshay ethay orldway...",
  "Tip4": "olouringcay ightslay...",
  "Tip5": "alvinghay absslay...",
  "Tip6": "opulatingpay ocksblay...",
  "Tip7": "ayeringlay unkschay...",
  "Tip8": "umulatingacc acespay ustday...",
  "Tip9": "Orbitingyay ubescay...",
  "Tip10": "atchingbay unkschay...",
  "Tip11": "urdlingcay ethay oonmay...",
  "Tip12": "e-clutteringday inventoriesyay...",
  "Tip13": "esnelfray-iicatingfay...",
  "Tip14": "olonizingcay anetsplay...",
  "Tip15": "iptay: ickpay ockblay usingyay ethay iddlemay ousemay uttonbay!",
  "Tip16": "iptay: ytray angingchay ethay ifferentday ightinglay odesmay inyay ethay ausepay enumay!",
  "Tip17": "iptay: esspray '$keybind_hideUI' otay idehay ethay useryay interfaceyay",
  "Tip18": "iptay: esspray '$keybind_screenshot' otay aketay ayay eenshotscray!",
  "Tip19": "iptay: esspray '$keybind_debugInfo' otay ooklay atyay ebuggingday informationyay",
  "Tip20": "iptay: esspray '$keybind_dropItem' otay opdray ethay urrentcay itemyay!",
  "Tip21": "iptay: esspray '$keybind_openInventory' otay openyay ethay inventoryyay!",
  "Tip22": "iptay: intspray againstyay ayay allway otay 'allway unray' , oinggay artherfay anthay ouyay ouldway onlyyay ybay umpingjay.",
  "OddTip1": "aftinggray ellscay...",
  "OddTip2": "Incubatingyay...",
  "OddTip3": "acrificingsay ubjectssay...",
  "OddTip4": "ountingcay eepshay...",
  "OddTip5": "iscardingday eceasedday issuetay...",
  "OddTip6": "arvestinghay emstay ellscay...",
  "OddTip7": "ollectingcay organyay \"onationsday\"...",
  "OddTip8": "observingyay icephaloustray...",
  "OddTip9": "epeatingray ialstray...",
  "OddTip10": "ategorizingcay ecimensspay...",
  "OddTip11": "iptay: ouyay annotcay ightfay againstyay entropyyay."
}
