=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/game.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/FinalForEach/Cosmic-Reach-Localization/master/assets/base/lang/game.schema.json",
  "title": "Cosmic Reach language (game.json)",
  "description": "FinalForEach's Cosmic Reach game localization language schema for game.json",
  "additionalProperties": false,
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "metadata": {
      "type": "object",
      "description": "Special metadata property for the language",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "description": "The language's name shown in the language menu"
        },
        "fallbacks": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true,
          "minItems": 0,
          "maxItems": 4,
          "description": "The language codes from which translations can be pulled from if missing keys in this file."
        }
      },
      "required": [
        "name"
      ]
    },
    "formatPercent": {
      "type": "string"
    },
    "startButton": {
      "type": "string"
    },
    "loadButton": {
      "type": "string"
    },
    "optionsButton": {
      "type": "string"
    },
    "quitButton": {
      "type": "string"
    },
    "vSyncButton": {
      "type": "string"
    },
    "creditsButton": {
      "type": "string"
    },
    "renderDistSlider": {
      "type": "string"
    },
    "invertedMouseButton": {
      "type": "string"
    },
    "mouseSensitivitySlider": {
      "type": "string"
    },
    "soundSlider": {
      "type": "string"
    },
    "musicSlider": {
      "type": "string"
    },
    "fovSlider": {
      "type": "string"
    },
    "musicFreqSlider": {
      "type": "string"
    },
    "maxFPS": {
      "type": "string"
    },
    "maxFPSUnlimited": {
      "type": "string"
    },
    "debugCrashButton": {
      "type": "string"
    },
    "keybindsButton": {
      "type": "string"
    },
    "difficultyButton": {
      "type": "string"
    },
    "difficultyPeaceful": {
      "type": "string"
    },
    "difficultyEasy": {
      "type": "string"
    },
    "difficultyNormal": {
      "type": "string"
    },
    "difficultyHard": {
      "type": "string"
    },
    "languagesButton": {
      "type": "string"
    },
    "rendererButton": {
      "type": "string"
    },
    "rendererNaive": {
      "type": "string"
    },
    "rendererBatched": {
      "type": "string"
    },
    "doneButton": {
      "type": "string"
    },
    "preAlphaText": {
      "type": "string"
    },
    "okButton": {
      "type": "string"
    },
    "Lighting": {
      "type": "string"
    },
    "Respawn": {
      "type": "string"
    },
    "YOU_ARE_DEAD": {
      "type": "string"
    },
    "Return_To_Game": {
      "type": "string"
    },
    "Return_To_Menu": {
      "type": "string"
    },
    "Saving": {
      "type": "string"
    },
    "Dynamic_Sky": {
      "type": "string"
    },
    "Space_Day": {
      "type": "string"
    },
    "Space_Sky": {
      "type": "string"
    },
    "Dark_Night": {
      "type": "string"
    },
    "Earth_Day": {
      "type": "string"
    },
    "Orange_Sky": {
      "type": "string"
    },
    "Pitch_Dark": {
      "type": "string"
    },
    "Overcast": {
      "type": "string"
    },
    "Forward": {
      "type": "string"
    },
    "Backward": {
      "type": "string"
    },
    "Left": {
      "type": "string"
    },
    "Right": {
      "type": "string"
    },
    "Jump": {
      "type": "string"
    },
    "Crouch": {
      "type": "string"
    },
    "Sprint": {
      "type": "string"
    },
    "Prone": {
      "type": "string"
    },
    "Inventory": {
      "type": "string"
    },
    "Cycle_Item_Type": {
      "type": "string"
    },
    "Drop_Item": {
      "type": "string"
    },
    "Hide_UI": {
      "type": "string"
    },
    "Screenshot": {
      "type": "string"
    },
    "Debug_Info": {
      "type": "string"
    },
    "Attack_Break": {
      "type": "string"
    },
    "Pick_Block": {
      "type": "string"
    },
    "Use_Place": {
      "type": "string"
    },
    "Open_Chat": {
      "type": "string"
    },
    "No_Clip": {
      "type": "string"
    },
    "Change_Perspective": {
      "type": "string"
    },
    "Reload_Shaders": {
      "type": "string"
    },
    "Fullscreen": {
      "type": "string"
    },
    "Create_New_World": {
      "type": "string"
    },
    "worldNameButton": {
      "type": "string"
    },
    "defaultWorldName": {
      "type": "string"
    },
    "worldSeedLabel": {
      "type": "string"
    },
    "worldSeedLabel2": {
      "type": "string"
    },
    "worldType": {
      "type": "string"
    },
    "Return_to_Main_Menu": {
      "type": "string"
    },
    "returnButton": {
      "type": "string"
    },
    "Open_Worlds_Directory": {
      "type": "string"
    },
    "YT_Channel": {
      "type": "string"
    },
    "Game_version_prealpha": {
      "type": "string"
    },
    "Game_version_alpha": {
      "type": "string"
    },
    "Game_version_beta": {
      "type": "string"
    },
    "Game_version_release": {
      "type": "string"
    },
    "MAC_warning": {
      "type": "string"
    },
    "Controller": {
      "type": "string"
    },
    "Controllers": {
      "type": "string"
    },
    "Controller_info": {
      "type": "string"
    },
    "on_state": {
      "type": "string"
    },
    "off_state": {
      "type": "string"
    },
    "World_name": {
      "type": "string"
    },
    "Screenshot_info": {
      "type": "string"
    },
    "Screenshot_error": {
      "type": "string"
    },
    "Loading": {
      "type": "string"
    },
    "mouseLeftButton": {
      "type": "string"
    },
    "mouseMiddleButton": {
      "type": "string"
    },
    "mouseRightButton": {
      "type": "string"
    },
    "mouseBackButton": {
      "type": "string"
    },
    "mouseForwardButton": {
      "type": "string"
    },
    "RuntimeException": {
      "type": "string"
    },
    "creditsGameBy": {
      "type": "string"
    },
    "creditsMusic": {
      "type": "string"
    },
    "creditsAdditionalProgramming": {
      "type": "string"
    },
    "creditsAdditionalModelling": {
      "type": "string"
    },
    "creditsAdditionalTexturing": {
      "type": "string"
    },
    "creditsAdditionalMobs": {
      "type": "string"
    },
    "creditsLocalization": {
      "type": "string"
    },
    "multiplayerButton": {
      "type": "string"
    },
    "multiplayerAddressButton": {
      "type": "string"
    },
    "multiplayerJoinButton": {
      "type": "string"
    },
    "multiplayerBadDisconnect": {
      "type": "string"
    },
    "textDisplayInput": {
      "type": "string"
    },
    "skinChangeLabel": {
      "type": "string"
    },
    "skinFileDesc": {
      "type": "string"
    },
    "itemCatalogSearch": {
      "type": "string"
    },
    "boomboxOctave": {
      "type": "string"
    },
    "boomboxPlaySound": {
      "type": "string"
    },
    "worldSelectionSearch": {
      "type": "string"
    },
    "createWorldGamemode": {
      "type": "string"
    },
    "gamemode_survival": {
      "type": "string"
    },
    "gamemode_creative": {
      "type": "string"
    },
    "zone_base:earth": {
      "type": "string"
    },
    "zone_base:flat": {
      "type": "string"
    },
    "zone_base:moon": {
      "type": "string"
    },
    "zone_base:nostalgic_island": {
      "type": "string"
    },
    "zone_base:void": {
      "type": "string"
    },
    "mobUnnamed": {
      "type": "string"
    },
    "zone_base:earth_legacy": {
      "type": "string"
    },
    "comingSoon": {
      "type": "string"
    },
    "langSelectionSearch": {
      "type": "string"
    },
    "worldDescriptionName": {
      "type": "string"
    },
    "worldDescriptionHeader": {
      "type": "string"
    },
    "worldDescriptionGamemode": {
      "type": "string"
    },
    "worldDescriptionGenerator": {
      "type": "string"
    },
    "worldDescriptionDefaultText": {
      "type": "string"
    },
    "worldSelectPlayWorld": {
      "type": "string"
    },
    "worldSelectSaveChanges": {
      "type": "string"
    },
    "loadingAssets": {
      "type": "string"
    },
    "loadingWorld": {
      "type": "string"
    },
    "multiplayerServerName": {
      "type": "string"
    },
    "multiplayerAddServer": {
      "type": "string"
    },
    "multiplayerNewServerDefaultName": {
      "type": "string"
    },
    "multiplayerDeleteServer": {
      "type": "string"
    },
    "multiplayerDeleteConfirmPrompt": {
      "type": "string"
    },
    "multiplayerEditServer": {
      "type": "string"
    },
    "genericSelectionSearch": {
      "type": "string"
    },
    "fullscreenModeButton": {
      "type": "string"
    },
    "fullscreenExclusive": {
      "type": "string"
    },
    "fullscreenBorderless": {
      "type": "string"
    }
  },
  "minProperties": 144
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/cs_cz/game.json
{
  "$schema": "https://raw.githubusercontent.com/FinalForEach/Cosmic-Reach-Localization/master/assets/base/lang/game.schema.json",
  "metadata": {
    "name": "Čeština",
    "fallbacks": [
      "sk_sk",
      "en_us"
    ]
  },
  "formatPercent": "# %",
  "startButton": "Hrát",
  "loadButton": "Otevřít ukládací adresář",
  "optionsButton": "Nastavení",
  "quitButton": "Ukončit",
  "vSyncButton": "Vertikální synchronizace: ",
  "creditsButton": "Zásluhy",
  "renderDistSlider": "Vzdálenost vykreslování: ",
  "invertedMouseButton": "Invertovat myš: ",
  "mouseSensitivitySlider": "Citlivost myši: ",
  "soundSlider": "Zvuk: ",
  "musicSlider": "Hudba: ",
  "musicFreqSlider": "Frekvence hudby v minutách: ",
  "fovSlider": "FOV: ",
  "maxFPS": "Limit FPS: ",
  "maxFPSUnlimited": "Limit FPS: Bez limitu",
  "debugCrashButton": "Debug: Crashnout hru",
  "keybindsButton": "Klávesové zkratky",
  "difficultyButton": "Obtížnost: ",
  "difficultyPeaceful": "mírumilovná",
  "difficultyEasy": "jednoduchá",
  "difficultyNormal": "normální",
  "difficultyHard": "těžká",
  "languagesButton": "Jazyk - Language",
  "rendererButton": "Renderování: ",
  "rendererNaive": "Základní",
  "rendererBatched": "Po částech",
  "doneButton": "Hotovo",
  "preAlphaText": "Vítejte ve hře Cosmic Reach! \n Hra je v ve velmi rané fázi vývoje, chybí jí mnohé funkce a není zdaleka kompletní. \n Hra nejspíše stále obsahuje bugy, glitche a crashe což může vést k poškození světa.\n Všechno se může změnit a nemusí odpovídat konečnému vzhledu hry.\n Je k dispozici pro Vás abyste mohli poskytnout zpětnou vazbu a pomoct řídit budoucnost této hry \n Šťastné testování... a rozbíjení hry!",
  "okButton": "Ok",
  "Lighting": "Osvětlení: ",
  "Respawn": "Respawnout",
  "YOU_ARE_DEAD": "JSTE MTRVÍ.",
  "Return_To_Game": "Zpět do hry",
  "Return_To_Menu": "Zpět do menu",
  "Saving": "Ukládám...",
  "Dynamic_Sky": "Dynamická obloha",
  "Space_Day": "Vesmírný den",
  "Dark_Night": "Temná noc",
  "Earth_Day": "Pozemský den",
  "Orange_Sky": "Oranžová obloha",
  "Pitch_Dark": "Úplná tma",
  "Overcast": "Zataženo",
  "Forward": "Dopředu",
  "Backward": "Dozadu",
  "Left": "Doleva",
  "Right": "Doprava",
  "Jump": "Skočit",
  "Crouch": "Přikrčit se",
  "Sprint": "Sprintovat",
  "Prone": "Lehnout si",
  "Inventory": "Inventář",
  "Cycle_Item_Type": "Cyklicky měnit typ předmětu",
  "Drop_Item": "Zahodit předmet",
  "Hide_UI": "Skrýt UI",
  "Screenshot": "Snímek obrazovky",
  "Debug_Info": "Debugovací informace",
  "Attack_Break": "Útok/ničení",
  "Pick_Block": "Vzít blok",
  "Use_Place": "Položit blok",
  "Open_Chat": "Otevřít chat",
  "No_Clip": "Spectator",
  "Change_Perspective": "Změnit perspektivu",
  "Reload_Shaders": "Znovu načíst shadery",
  "Fullscreen": "Na celou obrazovku",
  "Create_New_World": "Vytvořit nový svět",
  "worldNameButton": "Název světa: ",
  "defaultWorldName": "Nový Svět",
  "worldSeedLabel": "Seed světa: <náhodný>",
  "worldSeedLabel2": "Seed světa: ",
  "worldType": "Typ světa: ",
  "Return_to_Main_Menu": "Zpět do hlavního menu",
  "returnButton": "Zpět",
  "Open_Worlds_Directory": "Otevřít adresář světů",
  "YT_Channel": "Sleduj změny na youtube.com/@finalforeach",
  "Game_version_prealpha": "Cosmic Reach verze Pre-alpha-",
  "Game_version_alpha": "Cosmic Reach verze Alpha-",
  "Game_version_beta": "Cosmic Reach verze Beta-",
  "Game_version_release": "Cosmic Reach verze ",
  "MAC_warning": "UPOZORNĚNÍ: Mac není zatím podporován. Hra nejspíše nebude fungovat.",
  "Controller": "Ovladač detekován",
  "Controllers": "Ovladače detekovány",
  "Controller_info": "!\nPodpora ovladačů není ještě dokončená,\na bude vylepšena v budoucích updatech.",
  "on_state": "Zapnuto",
  "off_state": "Vypnuto",
  "World_name": "Svět-",
  "Screenshot_info": "Snímek obrazovky uložen do ",
  "Screenshot_error": "Nastala chyba při ukládáni snímku obrazovky.",
  "Loading": "Načítám",
  "mouseLeftButton": "Levé tlačítko",
  "mouseMiddleButton": "Střední tlačítko",
  "mouseRightButton": "Pravé tlačítko",
  "mouseBackButton": "Tlačítko dozadu",
  "mouseForwardButton": "Tlačítko dopředu",
  "RuntimeException": "Svět se nepovedlo načíst: ",
  "creditsGameBy": "AUTOR HRY:",
  "creditsMusic": "HUDBA:",
  "creditsAdditionalProgramming": "DALŠÍ PROGRAMOVÁNÍ:",
  "creditsAdditionalModelling": "DALŠÍ MODELOVÁNÍ:",
  "creditsAdditionalTexturing": "DALŠÍ GRAFIKA:",
  "creditsAdditionalMobs": "DALŠÍ MOBOVÉ:",
  "creditsLocalization": "LOKALIZACE:",
  "multiplayerButton": "Multiplayer",
  "multiplayerAddressButton": "Adresa serveru: ",
  "multiplayerJoinButton": "Připojit",
  "multiplayerBadDisconnect": "Byli jste odpojeni. Důvod:",
  "textDisplayInput": "Pište zde...",
  "skinChangeLabel": "Změnit skin",
  "skinFileDesc": "Soubor typu PNG se 128x64 pixely",
  "itemCatalogSearch": "Hledat...",
  "boomboxOctave": "Oktáva",
  "boomboxPlaySound": "Přehrát",
  "worldSelectionSearch": "Vyhledat Světy...",
  "createWorldGamemode": "Herní režim:",
  "gamemode_survival": "Přežití",
  "gamemode_creative": "Tvoření",
  "zone_base:earth": "Země",
  "zone_base:flat": "Placka",
  "zone_base:moon": "Měsíc",
  "zone_base:nostalgic_island": "Nostalgické Ostrovy",
  "zone_base:void": "Prázdný Svět",
  "mobUnnamed": "Nepojmenovaný",
  "zone_base:earth_legacy": "Země (Stará)"
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/fil_ph/game.json
{
  "$schema": "https://raw.githubusercontent.com/FinalForEach/Cosmic-Reach-Localization/master/assets/base/lang/game.schema.json",
  "metadata":
  {
    "name": "Filipino (Filipinas)",
    "fallbacks": ["tl_ph", "en_ph"]
  },
  "formatPercent": "#%",
  "startButton": "Magsimula",
  "loadButton": "Buksan ang Polder ng Save",
  "optionsButton": "Mga Opsyon",
  "quitButton": "Umalis",
  "vSyncButton": "Vsync: ",
  "creditsButton": "Mga Kredits",
  "renderDistSlider": "Layo ng Pagrerender: ",
  "invertedMouseButton": "Baliktarin ang Mouse: ",
  "mouseSensitivitySlider": "Paging sensitibo ng Mouse: ",
  "soundSlider": "Tinig: ",
  "musicSlider": "Musika: ",
  "fovSlider": "FOV: ",
  "maxFPS": "Max FPS: ",
  "maxFPSUnlimited": "Max FPS: Walang Limitasyon",
  "debugCrashButton": "Pagdebug: I-crash ang Laro",
  "keybindsButton": "Ayos ng Pindutan",
  "difficultyButton": "Hirap: ",
  "difficultyPeaceful": "Mapayapa",
  "difficultyEasy": "Madali",
  "difficultyNormal": "Katamtaman",
  "difficultyHard": "Mahirap",
  "languagesButton": "Wika",
  "rendererButton": "Renderer: ",
  "rendererNaive": "Naive",
  "rendererBatched": "Batched",
  "doneButton": "Tapos",
  "preAlphaText": "Maligayang pagdating sa Cosmic Reach! \n Nasa maagang yugto pa ang laro, maraming kulang, malayo pang makumpleto, \n at maaaring magkaroon ng mga bugs, teknikal na isyu, o kaya ay pagkasira ng mundo.\n Lahat ay pwede pang magbago at hindi kumakatawan sa huling anyo ng laro.\n Makakalaro ka upang makapagbigay katugunan at magabayan ang landas ng laro. \n Maligayang pagsubok... at pagkasira ng laro!",
  "okButton": "Sige",
  "Lighting": "Pag-iilaw: ",
  "Respawn": "Mabuhay muli",
  "YOU_ARE_DEAD": "NAMATAY KA.",
  "Return_To_Game": "Bumalik sa Laro",
  "Return_To_Menu": "Bumalik sa Menu",
  "Saving": "Sinasave...",
  "Dynamic_Sky": "Pabago-bagong Langit",
  "Space_Day": "Makalawakan",
  "Dark_Night": "Madilim na Gabi",
  "Earth_Day": "Araw ng Daigdig",
  "Orange_Sky": "Kahel na Langit",
  "Pitch_Dark": "Napakadilim",
  "Overcast": "Makulimlim",
  "Forward": "Pasulong",
  "Backward": "Umatras",
  "Left": "Kumaliwa",
  "Right": "Kumanan",
  "Jump": "Pagtalon",
  "Crouch": "Pagtago",
  "Sprint": "Pagtakbo",
  "Prone": "Dumapa",
  "Inventory": "Imbentaryo",
  "Cycle_Item_Type": "Baguhin ang Uri ng Bagay",
  "Drop_Item": "Bitawan ang Bagay",
  "Hide_UI": "Taguin ang UI",
  "Screenshot": "Magscreenshot",
  "Debug_Info": "Impormasyong pangdebug",
  "Attack_Break": "Umatake / Sumira",
  "Pick_Block": "Piliin ang Bloke",
  "Use_Place": "Gumamit / Maglagay",
  "Open_Chat": "Buksan ang Chat",
  "No_Clip": "Walang Banggaan",
  "Reload_Shaders": "I-reload ang mga Shaders",
  "Fullscreen": "Magfullscreen",
  "Create_New_World": "Gumawa ng Bagong Mudo",
  "worldNameButton": "Pangalan ng mundo: ",
  "defaultWorldName": "Bagong Mundo",
  "worldSeedLabel": "Binhi ng mundo: <Sapalaran>",
  "worldSeedLabel2": "Binhi ng mundo: ",
  "worldType": "Uri ng Mundo: ",
  "Return_to_Main_Menu": "Bumalik sa Panimulang Menu",
  "returnButton": "Bumalik",
  "Open_Worlds_Directory": "Buksan ang Direktoryo ng mga Mundo",
  "YT_Channel": "Panoorin ang mga devlogs sa youtube.com/@finalforeach",
  "Game_version_prealpha": "Cosmic Reach Bersyong Pre-alpha-",
  "MAC_warning": "BABALA: Hindi pa suportado ang Mac sa ngayon. Malamang hindi gagana ang laro.",
  "Controller": "Controller",
  "Controllers": "Controllers",
  "Controller_info": " ay nakita!\nHindi pa kumpleto ang suporta para sa mga controllers,\nat ipagpapabuti pa ito sa susunod na mga pagbabago.",
  "on_state": "Nakabukas",
  "off_state": "Nakapatay",
  "World_name": "Mundo-",
  "Screenshot_info": "Inilagay ang screenshot sa ",
  "Screenshot_error": "Umerror sa paglagay ng screenshot",
  "Loading": "Nag-loload",
  "mouseLeftButton" : "Kaliwang Pindutan",
  "mouseMiddleButton" : "Gitnang Pindutan",
  "mouseRightButton" : "Kanang Pindutan",
  "mouseBackButton" : "Pambalikang Pindutan",
  "mouseForwardButton" : "Pasulong na Pindutan",
  "RuntimeException": "Hindi ma-load ang mundong: ",
  "creditsGameBy": "LARO NI:",
  "creditsMusic": "MUSIKA:",
  "creditsAdditionalProgramming": "KARAGDAGANG PAGPROGRAMA:",
  "creditsAdditionalModelling": "KARAGDAGANG PAGMODELO:",
  "creditsAdditionalTexturing": "KARAGDAGANG PAGTEKSTURA:",
  "creditsLocalization": "LOKALISASYON:",
  "multiplayerButton": "Pangmaramihang Laro",
  "multiplayerAddressButton": "Address: ",
  "multiplayerJoinButton": "Sumali",
  "multiplayerBadDisconnect": "Nadisconnect! Dahilan:",
  "textDisplayInput": "Dito magsulat..."
}
