=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/game.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/FinalForEach/Cosmic-Reach-Localization/master/assets/base/lang/game.schema.json",
  "title": "Cosmic Reach language (game.json)",
  "description": "FinalForEach's Cosmic Reach game localization language schema for game.json",
  "additionalProperties": false,
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "metadata": {
      "type": "object",
      "description": "Special metadata property for the language",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "description": "The language's name shown in the language menu"
        },
        "fallbacks": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true,
          "minItems": 0,
          "maxItems": 4,
          "description": "The language codes from which translations can be pulled from if missing keys in this file."
        }
      },
      "required": [
        "name"
      ]
    },
    "formatPercent": {
      "type": "string"
    },
    "startButton": {
      "type": "string"
    },
    "loadButton": {
      "type": "string"
    },
    "optionsButton": {
      "type": "string"
    },
    "quitButton": {
      "type": "string"
    },
    "vSyncButton": {
      "type": "string"
    },
    "creditsButton": {
      "type": "string"
    },
    "renderDistSlider": {
      "type": "string"
    },
    "invertedMouseButton": {
      "type": "string"
    },
    "mouseSensitivitySlider": {
      "type": "string"
    },
    "soundSlider": {
      "type": "string"
    },
    "musicSlider": {
      "type": "string"
    },
    "fovSlider": {
      "type": "string"
    },
    "musicFreqSlider": {
      "type": "string"
    },
    "maxFPS": {
      "type": "string"
    },
    "maxFPSUnlimited": {
      "type": "string"
    },
    "debugCrashButton": {
      "type": "string"
    },
    "keybindsButton": {
      "type": "string"
    },
    "difficultyButton": {
      "type": "string"
    },
    "difficultyPeaceful": {
      "type": "string"
    },
    "difficultyEasy": {
      "type": "string"
    },
    "difficultyNormal": {
      "type": "string"
    },
    "difficultyHard": {
      "type": "string"
    },
    "languagesButton": {
      "type": "string"
    },
    "rendererButton": {
      "type": "string"
    },
    "rendererNaive": {
      "type": "string"
    },
    "rendererBatched": {
      "type": "string"
    },
    "doneButton": {
      "type": "string"
    },
    "preAlphaText": {
      "type": "string"
    },
    "okButton": {
      "type": "string"
    },
    "Lighting": {
      "type": "string"
    },
    "Respawn": {
      "type": "string"
    },
    "YOU_ARE_DEAD": {
      "type": "string"
    },
    "Return_To_Game": {
      "type": "string"
    },
    "Return_To_Menu": {
      "type": "string"
    },
    "Saving": {
      "type": "string"
    },
    "Dynamic_Sky": {
      "type": "string"
    },
    "Space_Day": {
      "type": "string"
    },
    "Space_Sky": {
      "type": "string"
    },
    "Dark_Night": {
      "type": "string"
    },
    "Earth_Day": {
      "type": "string"
    },
    "Orange_Sky": {
      "type": "string"
    },
    "Pitch_Dark": {
      "type": "string"
    },
    "Overcast": {
      "type": "string"
    },
    "Forward": {
      "type": "string"
    },
    "Backward": {
      "type": "string"
    },
    "Left": {
      "type": "string"
    },
    "Right": {
      "type": "string"
    },
    "Jump": {
      "type": "string"
    },
    "Crouch": {
      "type": "string"
    },
    "Sprint": {
      "type": "string"
    },
    "Prone": {
      "type": "string"
    },
    "Inventory": {
      "type": "string"
    },
    "Cycle_Item_Type": {
      "type": "string"
    },
    "Drop_Item": {
      "type": "string"
    },
    "Hide_UI": {
      "type": "string"
    },
    "Screenshot": {
      "type": "string"
    },
    "Debug_Info": {
      "type": "string"
    },
    "Attack_Break": {
      "type": "string"
    },
    "Pick_Block": {
      "type": "string"
    },
    "Use_Place": {
      "type": "string"
    },
    "Open_Chat": {
      "type": "string"
    },
    "No_Clip": {
      "type": "string"
    },
    "Change_Perspective": {
      "type": "string"
    },
    "Reload_Shaders": {
      "type": "string"
    },
    "Fullscreen": {
      "type": "string"
    },
    "Create_New_World": {
      "type": "string"
    },
    "worldNameButton": {
      "type": "string"
    },
    "defaultWorldName": {
      "type": "string"
    },
    "worldSeedLabel": {
      "type": "string"
    },
    "worldSeedLabel2": {
      "type": "string"
    },
    "worldType": {
      "type": "string"
    },
    "Return_to_Main_Menu": {
      "type": "string"
    },
    "returnButton": {
      "type": "string"
    },
    "Open_Worlds_Directory": {
      "type": "string"
    },
    "YT_Channel": {
      "type": "string"
    },
    "Game_version_prealpha": {
      "type": "string"
    },
    "Game_version_alpha": {
      "type": "string"
    },
    "Game_version_beta": {
      "type": "string"
    },
    "Game_version_release": {
      "type": "string"
    },
    "MAC_warning": {
      "type": "string"
    },
    "Controller": {
      "type": "string"
    },
    "Controllers": {
      "type": "string"
    },
    "Controller_info": {
      "type": "string"
    },
    "on_state": {
      "type": "string"
    },
    "off_state": {
      "type": "string"
    },
    "World_name": {
      "type": "string"
    },
    "Screenshot_info": {
      "type": "string"
    },
    "Screenshot_error": {
      "type": "string"
    },
    "Loading": {
      "type": "string"
    },
    "mouseLeftButton": {
      "type": "string"
    },
    "mouseMiddleButton": {
      "type": "string"
    },
    "mouseRightButton": {
      "type": "string"
    },
    "mouseBackButton": {
      "type": "string"
    },
    "mouseForwardButton": {
      "type": "string"
    },
    "RuntimeException": {
      "type": "string"
    },
    "creditsGameBy": {
      "type": "string"
    },
    "creditsMusic": {
      "type": "string"
    },
    "creditsAdditionalProgramming": {
      "type": "string"
    },
    "creditsAdditionalModelling": {
      "type": "string"
    },
    "creditsAdditionalTexturing": {
      "type": "string"
    },
    "creditsAdditionalMobs": {
      "type": "string"
    },
    "creditsLocalization": {
      "type": "string"
    },
    "multiplayerButton": {
      "type": "string"
    },
    "multiplayerAddressButton": {
      "type": "string"
    },
    "multiplayerJoinButton": {
      "type": "string"
    },
    "multiplayerBadDisconnect": {
      "type": "string"
    },
    "textDisplayInput": {
      "type": "string"
    },
    "skinChangeLabel": {
      "type": "string"
    },
    "skinFileDesc": {
      "type": "string"
    },
    "itemCatalogSearch": {
      "type": "string"
    },
    "boomboxOctave": {
      "type": "string"
    },
    "boomboxPlaySound": {
      "type": "string"
    },
    "worldSelectionSearch": {
      "type": "string"
    },
    "createWorldGamemode": {
      "type": "string"
    },
    "gamemode_survival": {
      "type": "string"
    },
    "gamemode_creative": {
      "type": "string"
    },
    "zone_base:earth": {
      "type": "string"
    },
    "zone_base:flat": {
      "type": "string"
    },
    "zone_base:moon": {
      "type": "string"
    },
    "zone_base:nostalgic_island": {
      "type": "string"
    },
    "zone_base:void": {
      "type": "string"
    },
    "mobUnnamed": {
      "type": "string"
    },
    "zone_base:earth_legacy": {
      "type": "string"
    },
    "comingSoon": {
      "type": "string"
    },
    "langSelectionSearch": {
      "type": "string"
    },
    "worldDescriptionName": {
      "type": "string"
    },
    "worldDescriptionHeader": {
      "type": "string"
    },
    "worldDescriptionGamemode": {
      "type": "string"
    },
    "worldDescriptionGenerator": {
      "type": "string"
    },
    "worldDescriptionDefaultText": {
      "type": "string"
    },
    "worldSelectPlayWorld": {
      "type": "string"
    },
    "worldSelectSaveChanges": {
      "type": "string"
    },
    "loadingAssets": {
      "type": "string"
    },
    "loadingWorld": {
      "type": "string"
    },
    "multiplayerServerName": {
      "type": "string"
    },
    "multiplayerAddServer": {
      "type": "string"
    },
    "multiplayerNewServerDefaultName": {
      "type": "string"
    },
    "multiplayerDeleteServer": {
      "type": "string"
    },
    "multiplayerDeleteConfirmPrompt": {
      "type": "string"
    },
    "multiplayerEditServer": {
      "type": "string"
    },
    "genericSelectionSearch": {
      "type": "string"
    },
    "fullscreenModeButton": {
      "type": "string"
    },
    "fullscreenExclusive": {
      "type": "string"
    },
    "fullscreenBorderless": {
      "type": "string"
    }
  },
  "minProperties": 144
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/it_it/game.json
{
    "$schema": "https://raw.githubusercontent.com/FinalForEach/Cosmic-Reach-Localization/master/assets/base/lang/game.schema.json",
    "metadata": {
        "name": "Italiano"
    },
    "formatPercent": "#%",
    "startButton": "Giocatore Singolo",
    "loadButton": "Apri la Cartella dei Salvataggi",
    "optionsButton": "Opzioni",
    "quitButton": "Esci",
    "vSyncButton": "Vsync: ",
    "creditsButton": "Crediti",
    "renderDistSlider": "Distanza di Rendering: ",
    "invertedMouseButton": "Inverti il Mouse: ",
    "mouseSensitivitySlider": "Sensibilità Mouse: ",
    "soundSlider": "Suoni: ",
    "musicSlider": "Musica: ",
    "fovSlider": "Campo Visivo: ",
    "musicFreqSlider": "Frequenza della Musica in Minuti:",
    "maxFPS": "FPS massimi: ",
    "maxFPSUnlimited": "FPS massimi: Illimitati",
    "debugCrashButton": "Debug: Crasha il gioco",
    "keybindsButton": "Associazione Tasti",
    "difficultyButton": "Difficoltà: ",
    "difficultyPeaceful": "Pacifica",
    "difficultyEasy": "Facile",
    "difficultyNormal": "Normale",
    "difficultyHard": "Difficile",
    "languagesButton": "Lingua",
    "rendererButton": "Renderer: ",
    "rendererNaive": "Non Ottimizzato",
    "rendererBatched": "Con Batching",
    "doneButton": "Fatto",
    "preAlphaText": "Benvenuto in Cosmic Reach! \n Il gioco è nella fase iniziale di sviluppo, mancano molte funzionalità e non è neanche lontanamente completo, \n probabilmente ci saranno bug, glitch, crash e corruzioni del Mondo.\n Tutto è soggetto a modifiche e non rappresenta il gioco finito.\n Puoi giocarci in modo da fornire feedback per aiutare a proseguire lo sviluppo del gioco \n Buon test... e rottura del Gioco!",
    "okButton": "Ok",
    "Lighting": "Illuminazione: ",
    "Respawn": "Rinasci",
    "YOU_ARE_DEAD": "SEI MORTO.",
    "Return_To_Game": "Riprendi A Giocare",
    "Return_To_Menu": "Ritorna Al Menù",
    "Saving": "Salvataggio in corso...",
    "Dynamic_Sky": "Cielo Dinamico",
    "Space_Day": "Giorno Spaziale",
    "Space_Sky": "Cielo Spaziale",
    "Dark_Night": "Notte Oscura",
    "Earth_Day": "Giorno Terrestre",
    "Orange_Sky": "Cielo Arancione",
    "Pitch_Dark": "Buio Pesto",
    "Overcast": "Nuvoloso",
    "Forward": "Cammina in avanti",
    "Backward": "Cammina all'indietro",
    "Left": "Sinistra",
    "Right": "Destra",
    "Jump": "Salta",
    "Crouch": "Accovacciati",
    "Sprint": "Corri",
    "Prone": "Sdraiati",
    "Inventory": "Inventario",
    "Cycle_Item_Type": "Cambia Tipo di Oggetto",
    "Drop_Item": "Rilascia l'Oggetto",
    "Hide_UI": "Nascondi l'Interfaccia",
    "Screenshot": "Screenshot",
    "Debug_Info": "Debug Info",
    "Attack_Break": "Attacca / Rompi",
    "Pick_Block": "Prendi blocco",
    "Use_Place": "Usa / Posiziona",
    "Open_Chat": "Apri la Chat",
    "No_Clip": "No-Clip",
    "Change_Perspective": "Cambia Prospettiva",
    "Reload_Shaders": "Ricarica le Shaders",
    "Fullscreen": "Schermo Intero",
    "Create_New_World": "Crea un Nuovo Mondo",
    "worldNameButton": "Nome del mondo: ",
    "defaultWorldName": "Nuovo Mondo",
    "worldSeedLabel": "Seme del mondo: <Casuale>",
    "worldSeedLabel2": "Seme del mondo: ",
    "worldType": "Tipo di Mondo: ",
    "Return_to_Main_Menu": "Ritorna al Menù Principale",
    "returnButton": "Indietro",
    "Open_Worlds_Directory": "Apri la Cartella dei Mondi",
    "YT_Channel": "Guarda i devlogs su youtube.com/@finalforeach",
    "Game_version_prealpha": "Cosmic Reach Versione Pre-alpha-",
    "Game_version_alpha": "Cosmic Reach Versione Alpha-",
    "Game_version_beta": "Cosmic Reach Versione Beta-",
    "Game_version_release": "Cosmic Reach Versione ",
    "MAC_warning": "AVVERTIMENTO: I Mac non sono supportati al momento. È probabile che il non gioco funzioni.",
    "Controller": "Controller",
    "Controllers": "Controller",
    "Controller_info": " rilevato!\nIl supporto dei controller è incompleto al momento,\ne sarà migliorato negli aggiornamenti futuri.",
    "on_state": "On",
    "off_state": "Off",
    "World_name": "Mondo-",
    "Screenshot_info": "Screenshot salvato in ",
    "Screenshot_error": "Errore nel salvataggio dello screenshot.",
    "Loading": "Caricamento",
    "mouseLeftButton": "Pulsante Sinistro",
    "mouseMiddleButton": "Pulsante Centrale",
    "mouseRightButton": "Pulsante Destro",
    "mouseBackButton": "Pulsante Indietro",
    "mouseForwardButton": "Pulsante Avanti",
    "RuntimeException": "Impossibile caricare il Mondo: ",
    "creditsGameBy": "GIOCO CREATO DA:",
    "creditsMusic": "MUSICHE:",
    "creditsAdditionalProgramming": "PROGRAMMAZIONE AGGIUNTIVA:",
    "creditsAdditionalModelling": "MODELLAZIONE AGGIUNTIVA:",
    "creditsAdditionalTexturing": "TEXTURIZZAZIONE AGGIUNTIVA:",
    "creditsAdditionalMobs": "MOB AGGIUNTIVI:",
    "creditsLocalization": "LOCALIZZAZIONE:",
    "multiplayerButton": "Multigiocatore",
    "multiplayerAddressButton": "Indirizzo: ",
    "multiplayerJoinButton": "Entra",
    "multiplayerBadDisconnect": "Disconnesso! Motivo:",
    "textDisplayInput": "Scrivi qui...",
    "skinChangeLabel": "Cambia la Tua Skin",
    "skinFileDesc": "File PNG di 128x64 pixel",
    "itemCatalogSearch": "Cerca...",
    "boomboxOctave": "Ottava",
    "boomboxPlaySound": "Riproduci",
    "worldSelectionSearch": "Cerca Mondi...",
    "createWorldGamemode": "Modalità di Gioco:",
    "gamemode_survival": "Sopravvivenza",
    "gamemode_creative": "Creativa",
    "zone_base:earth": "Terra",
    "zone_base:flat": "Piatto",
    "zone_base:moon": "Luna",
    "zone_base:nostalgic_island": "Isole Nostalgiche",
    "zone_base:void": "Mondo Vuoto",
    "mobUnnamed": "Senza Nome",
    "zone_base:earth_legacy": "Terra (Legacy)",
    "comingSoon": "Prossimamente...",
    "langSelectionSearch": "Cerca Lingue...",
    "worldDescriptionName": "Nome Mondo:",
    "worldDescriptionHeader": "Descrizione",
    "worldDescriptionGamemode": "Modalità:",
    "worldDescriptionGenerator": "Tipo Mondo:",
    "worldDescriptionDefaultText": "Inserisci la Descrizione del Mondo...",
    "worldSelectPlayWorld": "Gioca",
    "worldSelectSaveChanges": "Salva Cambiamenti",
    "loadingAssets": "Asset",
    "loadingWorld": "Mondo",
    "multiplayerServerName": "Nome Server: ",
    "multiplayerAddServer": "Aggiungi Server",
    "multiplayerNewServerDefaultName": "Nuovo Server",
    "multiplayerDeleteServer": "Elimina Server",
    "multiplayerDeleteConfirmPrompt": "Sei sicuro di voler eliminare {0}?",
    "multiplayerEditServer": "Modifica Server",
    "genericSelectionSearch": "Cerca..."
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/ko_kr/game.json
{
    "metadata": {
        "name": "한국어"
    },
    "formatPercent": "#%",
    "startButton": "싱글 플레이어",
    "loadButton": "세이브 데이터",
    "optionsButton": "옵션",
    "quitButton": "종료",
    "vSyncButton": "Vsync",
    "creditsButton": "크레딧",
    "renderDistSlider": "렌더 거리: ",
    "invertedMouseButton": "마우스 반전: ",
    "mouseSensitivitySlider": "마우스 감도: ",
    "soundSlider": "소리: ",
    "musicSlider": "BGM: ",
    "fovSlider": "FOV: ",
    "musicFreqSlider": "BGM 빈도: ",
    "maxFPS": "최대 FPS: ",
    "maxFPSUnlimited": "최대 FPS: 제한 없음",
    "debugCrashButton": "디버그: ",
    "keybindsButton": "조작키",
    "difficultyButton": "난이도: ",
    "difficultyPeaceful": "평화로움",
    "difficultyEasy": "쉬움",
    "difficultyNormal": "보통",
    "difficultyHard": "어려움",
    "languagesButton": "언어",
    "rendererButton": "렌더러: ",
    "rendererNaive": "단순/직접 처리",
    "rendererBatched": "일괄 처리",
    "doneButton": "완료",
    "preAlphaText": "코스믹 리치에 오신 것을 환영합니다! \n 이 게임은 개발 초기 단계에 있으며, 기능이 부족하고 완성도가 떨어집니다, \n 그리고 버그, 결함, 충돌 및 세계 붕괴가 발생할 가능성이 높습니다. \n 모든 요소는 변경될 수 있으며 최종 게임과 달라질 수 있습니다. \n 이 게임을 플레이하여 도움이 되는 피드백을 제공할 수 있습니다 \n 행복한 테스트 되세요!",
    "okButton": "확인",
    "Lighting": "밝기: ",
    "Respawn": "리스폰",
    "YOU_ARE_DEAD": "당신은 죽었습니다.",
    "Return_To_Game": "게임으로 돌아가기",
    "Return_To_Menu": "메뉴로 돌아가기",
    "Saving": "저장중...",
    "Dynamic_Sky": "다이나믹 스카이",
    "Space_Day": "스페이스 데이",
    "Dark_Night": "다크 나이트",
    "Earth_Day": "어스 데이",
    "Orange_Sky": "오렌지 스카이",
    "Pitch_Dark": "피치 다크",
    "Overcast": "오버캐스트",
    "Forward": "전진",
    "Backward": "후진",
    "Left": "좌",
    "Right": "우",
    "Jump": "점프",
    "Crouch": "앉기",
    "Sprint": "달리기",
    "Prone": "엎드리기",
    "Inventory": "가방",
    "Cycle_Item_Type": "아이템 종류 바꾸기",
    "Drop_Item": "아이템 버리기",
    "Hide_UI": "UI 숨기기",
    "Screenshot": "스크린샷",
    "Debug_Info": "디버그 정보",
    "Attack_Break": "공격 / 부수기",
    "Pick_Block": "블록 선택",
    "Use_Place": "사용 / 놓기",
    "Open_Chat": "대화 열기",
    "No_Clip": "노 클립",
    "Change_Perspective": "시점 변경",
    "Reload_Shaders": "셰이더 리로드",
    "Fullscreen": "풀스크린",
    "Create_New_World": "새로운 세계 생성",
    "worldNameButton": "월드 이름: ",
    "defaultWorldName": "새로운 세계",
    "worldSeedLabel": "월드 시드: <랜덤>",
    "worldSeedLabel2": "월드 시드: ",
    "worldType": "월드 타입: ",
    "Return_to_Main_Menu": "메인 메뉴로 돌아가기",
    "returnButton": "뒤로",
    "Open_Worlds_Directory": "월드 폴더 열기",
    "YT_Channel": "youtube.com/@finalforeach에서 개발 현황을 확인하세요",
    "Game_version_prealpha": "코스믹 리치 버전 Pre-alpha-",
    "Game_version_alpha": "코스믹 리치 버전 Alpha-",
    "Game_version_beta": "코스믹 리치 버전 Beta-",
    "Game_version_release": "코스믹 리지 버전",
    "MAC_warning": "주의: 지금은 맥OS를 지원하지 않습니다. 게임이 올바르게 작동될 가능성이 낮습니다.",
    "Controller": "컨트롤러",
    "Controllers": "컨트롤러",
    "Controller_info": "감지됨!\n아직 컨트롤러 지원이 부족합니다,\n추후 업데이트를 통해 개선됩니다.",
    "on_state": "켬",
    "off_state": "끔",
    "World_name": "세계-",
    "Screenshot_info": "스크린샷을 저장했습니다",
    "Screenshot_error": "스크린샷 저장중 문제가 발생하였습니다.",
    "Loading": "로딩중",
    "mouseLeftButton": "왼쪽 버튼",
    "mouseMiddleButton": "가운데 버튼",
    "mouseRightButton": "오른쪽 버튼",
    "mouseBackButton": "마우스 버튼 4",
    "mouseForwardButton": "마우스 버튼 5",
    "RuntimeException": "월드를 불러오지 못했습니다: ",
    "creditsGameBy": "게임 제작:",
    "creditsMusic": "음악:",
    "creditsAdditionalProgramming": "프로그래밍 참여:",
    "creditsAdditionalModelling": "모델림 참여:",
    "creditsAdditionalTexturing": "텍스쳐링 참여:",
    "creditsAdditionalMobs": "몹 디자인 참여:",
    "creditsLocalization": "현지화 참여:",
    "multiplayerButton": "멀티 플레이어",
    "multiplayerAddressButton": "주소: ",
    "multiplayerJoinButton": "참가",
    "multiplayerBadDisconnect": "연결 끊김! 사유:",
    "textDisplayInput": "여기에 입력...",
    "skinChangeLabel": "스킨 변경",
    "skinFileDesc": "128x64 픽셀의 PNG 파일",
    "itemCatalogSearch": "검색...",
    "boomboxOctave": "옥타브",
    "boomboxPlaySound": "재생",
    "worldSelectionSearch": "월드 검색...",
    "createWorldGamemode": "게임 모드:",
    "gamemode_survival": "서바이벌",
    "gamemode_creative": "크리에이티브",
    "zone_base:earth": "지구",
    "zone_base:flat": "평지",
    "zone_base:moon": "달",
    "zone_base:void": "공허",
    "mobUnnamed": "언네임드",
    "zone_base:earth_legacy": "지구 (레거시)",
    "comingSoon": "곧 공개...",
    "zone_base:nostalgic_island": "그리운 섬"
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/id_id/game.json
{
  "$schema": "../game.schema.json",
  "metadata": {
    "name": "Indonesia"
  },
  "formatPercent": "#%",
  "startButton": "Bermain Sendiri",
  "loadButton": "Buka Direktori Penyimpanan",
  "optionsButton": "Opsi",
  "quitButton": "Keluar",
  "vSyncButton": "Vsync: ",
  "creditsButton": "Kredit",
  "renderDistSlider": "Jarak Render: ",
  "invertedMouseButton": "Mouse Terbalik: ",
  "mouseSensitivitySlider": "Sensitivitas Mouse: ",
  "soundSlider": "Suara: ",
  "musicSlider": "Musik: ",
  "fovSlider": "FOV: ",
  "musicFreqSlider": "Kekerapan Musik dalam Menit: ",
  "maxFPS": "FPS Maksimum: ",
  "maxFPSUnlimited": "FPS Maksimum: Tak Terbatas",
  "debugCrashButton": "Debug: Paksa permainan crash",
  "keybindsButton": "Pengaturan Tombol",
  "difficultyButton": "Kesulitan: ",
  "difficultyPeaceful": "Damai",
  "difficultyEasy": "Mudah",
  "difficultyNormal": "Normal",
  "difficultyHard": "Sulit",
  "languagesButton": "Bahasa",
  "rendererButton": "Renderer: ",
  "rendererNaive": "Naive",
  "rendererBatched": "Batched",
  "doneButton": "Selesai",
  "preAlphaText": "Selamat datang di Cosmic Reach! \n Permainan ini masih dalam tahap pengembangan awal, masih kekurangan fitur, belum sepenuhnya selesai, \n dan kemungkinan besar akan memiliki bug, glitch, crash, dan kerusakan dunia permainan.\n Segala hal dapat berubah sewaktu-waktu dan belum mencerminkan versi final permainan ini.\n Permainan ini tersedia untuk kamu mainkan agar kamu dapat memberikan umpan balik untuk membantu memandu pengembangan permainan ini di masa mendatang.\n Selamat mencoba... dan merusak permainan!",
  "okButton": "Ok",
  "Lighting": "Pencahayaan: ",
  "Respawn": "Muncul kembali",
  "YOU_ARE_DEAD": "KAMU TELAH MATI.",
  "Return_To_Game": "Kembali ke Permainan",
  "Return_To_Menu": "Kembali ke Menu",
  "Saving": "Menyimpan...",
  "Dynamic_Sky": "Langit Dinamis",
  "Space_Day": "Siang Antariksa",
  "Space_Sky": "Langit Antariksa",
  "Dark_Night": "Malam Gelap",
  "Earth_Day": "Siang Bumi",
  "Orange_Sky": "Langit Jingga",
  "Pitch_Dark": "Gelap Gulita",
  "Overcast": "Mendung",
  "Forward": "Maju",
  "Backward": "Mundur",
  "Left": "Kiri",
  "Right": "Kanan",
  "Jump": "Lompat",
  "Crouch": "Jongkok",
  "Sprint": "Lari",
  "Prone": "Tengkurap",
  "Inventory": "Persediaan",
  "Cycle_Item_Type": "Ganti Jenis Item",
  "Drop_Item": "Jatuhkan Barang",
  "Hide_UI": "Sembunyikan UI",
  "Screenshot": "Tangkapan Layar",
  "Debug_Info": "Informasi Debug",
  "Attack_Break": "Serang / Hancurkan",
  "Pick_Block": "Pilih Blok",
  "Use_Place": "Gunakan / Tempatkan",
  "Open_Chat": "Buka Obrolan",
  "No_Clip": "No-Clip",
  "Change_Perspective": "Ubah Perspektif",
  "Reload_Shaders": "Muat Ulang Shader",
  "Fullscreen": "Layar Penuh",
  "Create_New_World": "Buat Dunia Baru",
  "worldNameButton": "Nama Dunia: ",
  "defaultWorldName": "Dunia Baru",
  "worldSeedLabel": "Benih Dunia: <Acak>",
  "worldSeedLabel2": "Benih Dunia: ",
  "worldType": "Jenis Dunia: ",
  "Return_to_Main_Menu": "Kembali ke Menu Utama",
  "returnButton": "Kembali",
  "Open_Worlds_Directory": "Buka Direktori Dunia",
  "YT_Channel": "Tonton video devlog di youtube.com/@finalforeach",
  "Game_version_prealpha": "Cosmic Reach Versi Pra-alpha-",
  "Game_version_alpha": "Cosmic Reach Versi Alpha-",
  "Game_version_beta": "Cosmic Reach Versi Beta-",
  "Game_version_release": "Cosmic Reach Versi ",
  "MAC_warning": "PERINGATAN: Mac belum didukung saat ini. Permainan ini kemungkinan besar tidak akan berfungsi.",
  "Controller": "Pengontrol",
  "Controllers": "Beberapa pengontrol",
  "Controller_info": " terdeteksi!\nDukungan pengontrol saat ini belum lengkap,\ndan akan ditingkatkan pada masa mendatang.",
  "on_state": "Hidup",
  "off_state": "Mati",
  "World_name": "Dunia-",
  "Screenshot_info": "Tangkapan layar disimpan ke ",
  "Screenshot_error": "Terjadi kesalahan saat menyimpan tangkapan layar.",
  "Loading": "Memuat",
  "mouseLeftButton": "Tombol Kiri",
  "mouseMiddleButton": "Tombol Tengah",
  "mouseRightButton": "Tombol Kanan",
  "mouseBackButton": "Tombol Belakang",
  "mouseForwardButton": "Tombol Depan",
  "RuntimeException": "Tidak dapat memuat dunia: ",
  "creditsGameBy": "GAME BY:",
  "creditsMusic": "MUSIC:",
  "creditsAdditionalProgramming": "ADDITIONAL PROGRAMMING:",
  "creditsAdditionalModelling": "ADDITIONAL MODELLING:",
  "creditsAdditionalTexturing": "ADDITIONAL TEXTURING:",
  "creditsAdditionalMobs": "ADDITIONAL MOBS:",
  "creditsLocalization": "LOCALIZATION:",
  "multiplayerButton": "Bermain Bersama",
  "multiplayerAddressButton": "Alamat: ",
  "multiplayerJoinButton": "Bergabung",
  "multiplayerBadDisconnect": "Terputus! Alasan:",
  "textDisplayInput": "Ketik di sini...",
  "skinChangeLabel": "Ubah Skin",
  "skinFileDesc": "Berkas PNG dengan ukuran 128x64 piksel",
  "itemCatalogSearch": "Telusuri...",
  "boomboxOctave": "Oktaf",
  "boomboxPlaySound": "Mainkan",
  "worldSelectionSearch": "Telusuri Dunia...",
  "createWorldGamemode": "Mode Permainan:",
  "gamemode_survival": "Sintas",
  "gamemode_creative": "Kreatif",
  "zone_base:earth": "Bumi",
  "zone_base:flat": "Datar",
  "zone_base:moon": "Bulan",
  "zone_base:nostalgic_island": "Pulau-Pulau Nostalgia",
  "zone_base:void": "Dunia Hampa",
  "mobUnnamed": "Tanpa Nama",
  "zone_base:earth_legacy": "Bumi (Lawas)",
  "comingSoon": "Segera hadir...",
  "langSelectionSearch": "Telusuri Bahasa...",
  "worldDescriptionName": "Nama Dunia:",
  "worldDescriptionHeader": "Deskripsi",
  "worldDescriptionGamemode": "Mode Permainan: ",
  "worldDescriptionGenerator": "Jenis Dunia: ",
  "worldDescriptionDefaultText": "Masukkan Deskripsi Dunia...",
  "worldSelectPlayWorld": "Bermain",
  "worldSelectSaveChanges": "Simpan Perubahan",
  "loadingAssets": "Aset",
  "loadingWorld": "Dunia",
  "multiplayerServerName": "Nama Peladen: ",
  "multiplayerAddServer": "Tambah Peladen",
  "multiplayerNewServerDefaultName": "Peladen Baru",
  "multiplayerDeleteServer": "Hapus Peladen",
  "multiplayerDeleteConfirmPrompt": "Apakah kamu yakin ingin menghapus {0}?",
  "multiplayerEditServer": "Sunting Peladen",
  "genericSelectionSearch": "Telusuri..."
}
