=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/odd-tips.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/FinalForEach/Cosmic-Reach-Localization/master/assets/base/lang/odd-tips.schema.json",
  "title": "Cosmic Reach language (odd tips)",
  "description": "FinalForEach's Cosmic Reach game localization language schema for odd-tips.json",
  "type": "object",
  "additionalProperties": false,
  "__HOW_TO_ADD_PROPERTY__": "First, copy-paste a previous property ({type: 'string'} etc.), then change its key. Then update the minProperties field below to match the total count of the defined properties. (e.g. add 1 if you add 1 text etc.)",
  "__SCHEMA_DOCS__": "https://json-schema.org/understanding-json-schema/reference",
  "minProperties": 11,
  "properties": {
    "$schema": {
      "type": "string",
      "description": "Special property defining this schema as the schema of the language, e.g. should be same to the root $id property. Since this field does count to the total root minProperties property, it is required.",
      "const": "https://raw.githubusercontent.com/FinalForEach/Cosmic-Reach-Localization/master/assets/base/lang/odd-tips.schema.json"
    },
    "OddTip1": {
      "type": "string"
    },
    "OddTip2": {
      "type": "string"
    },
    "OddTip3": {
      "type": "string"
    },
    "OddTip4": {
      "type": "string"
    },
    "OddTip5": {
      "type": "string"
    },
    "OddTip6": {
      "type": "string"
    },
    "OddTip7": {
      "type": "string"
    },
    "OddTip8": {
      "type": "string"
    },
    "OddTip9": {
      "type": "string"
    },
    "OddTip10": {
      "type": "string"
    },
    "OddTip11": {
      "type": "string"
    }
  }
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/et_et/spoilers/odd-tips.json
{
  "OddTip1": "Rakkude siirdamine...",
  "OddTip2": "Inkubeerimine...",
  "OddTip3": "Ohvrite ohverdamine...",
  "OddTip4": "Lammaste lugemine...",
  "OddTip5": "Surnud kudeme 채raviskamine...",
  "OddTip6": "T체virakkude koristamine...",
  "OddTip7": "\"Elundidoonorluste\" korjamine...",
  "OddTip8": "Tricephalouse j채lgimine...",
  "OddTip9": "Katsete kordamine...",
  "OddTip10": "Eksemplaride kategoriseerimine...",
  "OddTip11": "Vihje: Entroopia vastu v천itlemine on kasutu."
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/bel_bel/spoilers/odd-tips.json
{
    "OddTip1": "Перасаджваем клеткі...",
    "OddTip2": "Інкубуем...",
    "OddTip3": "Жэртвуем суб'ектамі...",
    "OddTip4": "Лічым авечак...",
    "OddTip5": "Выкідваем мёртвую тканіну...",
    "OddTip6": "Збіраем ствалавыя клеткі...",
    "OddTip7": "Збіраем \"ахвяраванні\" органаў...",
    "OddTip8": "Глядзім на трыцэфала...",
    "OddTip9": "Паўтараем выпрабаванні...",
    "OddTip10": "Класіфікуем асобнікі...",
    "OddTip11": "Падказка: Ты не можаш змагацца з энтрапіяй."
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/ro_ro/spoilers/odd-tips.json
{
    "OddTip1": "Se atașează celule...",
    "OddTip2": "Se incubează...",
    "OddTip3": "Se sacrifică subiecții...",
    "OddTip4": "Se numără oi...",
    "OddTip5": "Se aruncă țesut mort...",
    "OddTip6": "Se recoltează celule stem...",
    "OddTip7": "Se colectează \"donații\" de organe...",
    "OddTip8": "Se observă tricefalul...",
    "OddTip9": "Se repetă probele...",
    "OddTip10": "Se categorisesc specimenele...",
    "OddTip11": "Tip: Nu poți lupta împotriva entropiei."
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/fr_fr/spoilers/odd-tips.json
{
  "OddTip1": "Greffe de cellules...",
  "OddTip2": "Incubation...",
  "OddTip3": "Sacrifice des sujets...",
  "OddTip4": "Comptage de moutons ...",
  "OddTip5": "Élimination des tissus décédés...",
  "OddTip6": "Prélèvement de cellules souches...",
  "OddTip7": "Collecte d'organes généreusement \"donnés\"...",
  "OddTip8": "Observation des tricéphales...",
  "OddTip9": "Répétition des essais...",
  "OddTip10": "Catégorisation des spécimens...",
  "OddTip11": "Conseil : Tu ne peux pas lutter contre l'entropie."
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/eo_eo/spoilers/odd-tips.json
{
    "OddTip1": "Greftante ĉelojn...",
    "OddTip2": "Kovanta...",
    "OddTip3": "Oferante temojn...",
    "OddTip4": "Nombri ŝafojn...",
    "OddTip5": "Forĵetante forpasintan teksaĵon...",
    "OddTip6": "Rikolti stamĉelojn...",
    "OddTip7": "Kolekti \"donacojn\" de organoj...",
    "OddTip8": "Observante persono kun tri kapoj...",
    "OddTip9": "Ripetantaj provoj...",
    "OddTip10": "Kategoriiganta specimenojn...",
    "OddTip11": "Konsileto: Vi ne povas batali kontraŭ entropio."
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/el_el/spoilers/odd-tips.json
{
  "OddTip1": "Κύτταρα εμβολιασμού...",
  "OddTip2": "Επώαση...",
  "OddTip3": "Θυσία θεμάτων...",
  "OddTip4": "Μετράω προβατάκια...",
  "OddTip5": "Απόρριψη νεκρού ιστού...",
  "OddTip6": "Συγκομιδή βλαστοκυττάρων...",
  "OddTip7": "Συλλογή οργάνων \"δωρεές\"...",
  "OddTip8": "Παρατηρώντας τρικέφαλο...",
  "OddTip9": "Επαναλαμβανόμενες δοκιμές...",
  "OddTip10": "Ταξινόμηση δειγμάτων...",
  "OddTip11": "Συμβουλή: Δεν μπορείτε να πολεμήσετε την εντροπία"
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/cy_gb/spoilers/odd-tips.json
{
  "OddTip1": "Grefftio celloedd...",
  "OddTip2": "Deori...",
  "OddTip3": "Aberthu pynciau...",
  "OddTip4": "Cyfrif defaid...",
  "OddTip5": "Gwaredu meinwe ymadawedig...",
  "OddTip6": "Cynaeafu b√¥n-gelloedd...",
  "OddTip7": "Casglu \"rhoddion\" organau...",
  "OddTip8": "Arsylwi tricephalous...",
  "OddTip9": "Treialon ailadroddus...",
  "OddTip10": "Categoreiddio sbesimenau...",
  "OddTip11": "Awgrym: Ni allwch ymladd yn erbyn entropi."
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/da_dk/spoilers/odd-tips.json
{
    "OddTip1": "Poder celler...",
    "OddTip2": "Inkuberer...",
    "OddTip3": "Ofre undersåttere...",
    "OddTip4": "Tæller får...",
    "OddTip5": "Forkaster ødelagt væv...",
    "OddTip6": "Høster stamceller...",
    "OddTip7": "Samler organ\"donationer\"...",
    "OddTip8": "Iagttager tricephalous...",
    "OddTip9": "Gentager tests...",
    "OddTip10": "Kategoriserer organismer...",
    "OddTip11": "Tip: Kampen mod entropi er ikke en som du kan vinde.."
}
