=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/odd-tips.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/FinalForEach/Cosmic-Reach-Localization/master/assets/base/lang/odd-tips.schema.json",
  "title": "Cosmic Reach language (odd tips)",
  "description": "FinalForEach's Cosmic Reach game localization language schema for odd-tips.json",
  "type": "object",
  "additionalProperties": false,
  "__HOW_TO_ADD_PROPERTY__": "First, copy-paste a previous property ({type: 'string'} etc.), then change its key. Then update the minProperties field below to match the total count of the defined properties. (e.g. add 1 if you add 1 text etc.)",
  "__SCHEMA_DOCS__": "https://json-schema.org/understanding-json-schema/reference",
  "minProperties": 11,
  "properties": {
    "$schema": {
      "type": "string",
      "description": "Special property defining this schema as the schema of the language, e.g. should be same to the root $id property. Since this field does count to the total root minProperties property, it is required.",
      "const": "https://raw.githubusercontent.com/FinalForEach/Cosmic-Reach-Localization/master/assets/base/lang/odd-tips.schema.json"
    },
    "OddTip1": {
      "type": "string"
    },
    "OddTip2": {
      "type": "string"
    },
    "OddTip3": {
      "type": "string"
    },
    "OddTip4": {
      "type": "string"
    },
    "OddTip5": {
      "type": "string"
    },
    "OddTip6": {
      "type": "string"
    },
    "OddTip7": {
      "type": "string"
    },
    "OddTip8": {
      "type": "string"
    },
    "OddTip9": {
      "type": "string"
    },
    "OddTip10": {
      "type": "string"
    },
    "OddTip11": {
      "type": "string"
    }
  }
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/fi_fi/spoilers/odd-tips.json
{
  "OddTip1": "Siirretään soluja...",
  "OddTip2": "Haudotaan...",
  "OddTip3": "Suoritetaan uhrauksia...",
  "OddTip4": "Lasketaan lampaita...",
  "OddTip5": "Hävitetään kuollutta kudosta...",
  "OddTip6": "Kerätään kantasoluja...",
  "OddTip7": "Kerätään \"elinluovutuksia\"...",
  "OddTip8": "Tarkkailaan tricephalousta...",
  "OddTip9": "Toistetaan kokeita...",
  "OddTip10": "Luokitellaan näytteitä...",
  "OddTip11": "Vihje: entropiaa vastaan kamppailu on turhaa."
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/hr_hr/spoilers/odd-tips.json
{
    "OddTip1": "Kalemljenje stanica...",
    "OddTip2": "Inkubiranje...",
    "OddTip3": "Žrtvovanje subjekata...",
    "OddTip4": "Brojanje ovaca...",
    "OddTip5": "Odbacivanje mrtvog tkiva...",
    "OddTip6": "Skupljanje matičnih stanica...",
    "OddTip7": "Skupljanje \"donacija\" organa...",
    "OddTip8": "Promatranje tricefalusa...",
    "OddTip9": "Ponavljanje proba...",
    "OddTip10": "Svrstavanje specimena...",
    "OddTip11": "Savjet: Ne možeš se boriti protiv entropije."
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/lv_lv/spoilers/odd-tips.json
{
    "OddTip1": "Potē šūnas...",
    "OddTip2": "Inkubē...",
    "OddTip3": "Upurē izmēģinājuma trusīšus...",
    "OddTip4": "Skaita aitas...",
    "OddTip5": "Utilizē satrupējušos audus...",
    "OddTip6": "Ievāc cilmes šūnas...",
    "OddTip7": "Ievāc orgānu \"donorus\"...",
    "OddTip8": "Pēta leviatānu...",
    "OddTip9": "Atkārto piegājienus...",
    "OddTip10": "Kategorizē īpatņus...",
    "OddTip11": "Knifs: Entropijai nepretosies."
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/pt_br/spoilers/odd-tips.json
{
  "OddTip1": "Criando células...",
  "OddTip2": "Incubando...",
  "OddTip3": "Sacrificando cobaias...",
  "OddTip4": "Contando ovelhas...",
  "OddTip5": "Jogando fora tecido morto...",
  "OddTip6": "Colhendo células tronco...",
  "OddTip7": "Coletando \"doações\" de orgãos...",
  "OddTip8": "Observando tricéfalo...",
  "OddTip9": "Repetindo testes...",
  "OddTip10": "Categorizando espécies...",
  "OddTip11": "Dica: Você não pode lutar contra a entropia."
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/tl_ph/spoilers/odd-tips.json
{
  "OddTip1": "Naghúhugpóng ng mga síhay...",
  "OddTip2": "Naglumílimlím...",
  "OddTip3": "Hinahandóg ang mga sákop...",
  "OddTip4": "Nagbíbiláng ng túpa...",
  "OddTip5": "Tinátanggál ang mga nasawíng síhayan...",
  "OddTip6": "Umaáni ng mga púnungtangkáyang síhay...",
  "OddTip7": "Nagtitípon ng mga \"pinagkaloóbang\" tátag...",
  "OddTip8": "Pinagmámasdán ang matatlóng-úlo...",
  "OddTip9": "Inuúlit-úlit ang mga pagsúbok...",
  "OddTip10": "Nag-uúrí-urí ng mga lakdá...",
  "OddTip11": "Hiwátig: Hindî mo malalabánan ang malikusóg."
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/nb_no/spoilers/odd-tips.json
{
  "OddTip1": "Transplanterer celler...",
  "OddTip2": "Inkuberer...",
  "OddTip3": "Ofrer forsøkspersoner...",
  "OddTip4": "Teller sauer...",
  "OddTip5": "Kasserer dødt vev...",
  "OddTip6": "Høster stamceller...",
  "OddTip7": "Samler organ\"donasjoner\"...",
  "OddTip8": "Observerer Tricephalous...",
  "OddTip9": "Gjentar prøvelser...",
  "OddTip10": "Kategoriserer eksemplarer...",
  "OddTip11": "Tips: Du kan ikke kjempe imot entropi."
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/sv_se/spoilers/odd-tips.json
{
  "OddTip1": "Okulerar celler...",
  "OddTip2": "Inkuberar...",
  "OddTip3": "Offrar subjekt...",
  "OddTip4": "Räknar lamm...",
  "OddTip5": "Kasserar död vävnad...",
  "OddTip6": "Skördar stamceller...",
  "OddTip7": "Samlar organ \"donationer\"...",
  "OddTip8": "Observerar tricefalus...",
  "OddTip9": "Upprepar prov...",
  "OddTip10": "Kategoriserar provexemplar...",
  "OddTip11": "Tips: Du kan inte förhindra entropi."
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/nn_no/spoilers/odd-tips.json
{
  "OddTip1": "Transplanterer celler...",
  "OddTip2": "Inkuberer...",
  "OddTip3": "Ofrar forsøkspersonar...",
  "OddTip4": "Tel sauer...",
  "OddTip5": "Kasserar dødt vev...",
  "OddTip6": "Haustar stamceller...",
  "OddTip7": "Samlar organ\"donasjonar\"...",
  "OddTip8": "Observerer Tricephalous...",
  "OddTip9": "Gjentek prøvelsar...",
  "OddTip10": "Kategoriserer eksemplar...",
  "OddTip11": "Tips: Du kan ikkje kjempa imot entropi."
}
