=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/odd-tips.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/FinalForEach/Cosmic-Reach-Localization/master/assets/base/lang/odd-tips.schema.json",
  "title": "Cosmic Reach language (odd tips)",
  "description": "FinalForEach's Cosmic Reach game localization language schema for odd-tips.json",
  "type": "object",
  "additionalProperties": false,
  "__HOW_TO_ADD_PROPERTY__": "First, copy-paste a previous property ({type: 'string'} etc.), then change its key. Then update the minProperties field below to match the total count of the defined properties. (e.g. add 1 if you add 1 text etc.)",
  "__SCHEMA_DOCS__": "https://json-schema.org/understanding-json-schema/reference",
  "minProperties": 11,
  "properties": {
    "$schema": {
      "type": "string",
      "description": "Special property defining this schema as the schema of the language, e.g. should be same to the root $id property. Since this field does count to the total root minProperties property, it is required.",
      "const": "https://raw.githubusercontent.com/FinalForEach/Cosmic-Reach-Localization/master/assets/base/lang/odd-tips.schema.json"
    },
    "OddTip1": {
      "type": "string"
    },
    "OddTip2": {
      "type": "string"
    },
    "OddTip3": {
      "type": "string"
    },
    "OddTip4": {
      "type": "string"
    },
    "OddTip5": {
      "type": "string"
    },
    "OddTip6": {
      "type": "string"
    },
    "OddTip7": {
      "type": "string"
    },
    "OddTip8": {
      "type": "string"
    },
    "OddTip9": {
      "type": "string"
    },
    "OddTip10": {
      "type": "string"
    },
    "OddTip11": {
      "type": "string"
    }
  }
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/sr_sp/spoilers/odd-tips.json
{
    "OddTip1": "Пресађивање ћелија...",
    "OddTip2": "Инкубирање...",
    "OddTip3": "Жртвовање поданика...",
    "OddTip4": "Бројање оваца...",
    "OddTip5": "Одбацивање мртвог ткива...",
    "OddTip6": "Прикупљање матичних ћелија...",
    "OddTip7": "Прикпуљање органских \"донација\"...",
    "OddTip8": "Гледање трикефалоса...",
    "OddTip9": "Понављање експеримената...",
    "OddTip10": "Категоризирање примерака...",
    "OddTip11": "Савет: Не можеш се борити против ентропије."
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/pt_pt/spoilers/odd-tips.json
{
  "OddTip1": "A enxertar células...",
  "OddTip2": "A incubar...",
  "OddTip3": "A sacrificar cobaias...",
  "OddTip4": "A contar ovelhas...",
  "OddTip5": "A descartar tecido morto...",
  "OddTip6": "A colher células-tronco...",
  "OddTip7": "A coletar \"doações\" de orgãos...",
  "OddTip8": "A observar tricéfalos...",
  "OddTip9": "A repetir ensaios...",
  "OddTip10": "A categorizar espécimes...",
  "OddTip11": "Dica: Não consegues lutar contra a entropia."
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/en_pirate/spoilers/odd-tips.json
{
    "OddTip1": "Grafting cells...",
    "OddTip2": "Incubating...",
    "OddTip3": "Sacrificing subjects...",
    "OddTip4": "Counting sheep...",
    "OddTip5": "Discarding deceased tissue...",
    "OddTip6": "Harvesting stem cells...",
    "OddTip7": "Collecting organ \"donations\"...",
    "OddTip8": "Observing tricephalous...",
    "OddTip9": "Repeating trials...",
    "OddTip10": "Categorizing specimens...",
    "OddTip11": "Tip: You cannot fight against entropy."
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/hu_hu/spoilers/odd-tips.json
{
  "OddTip1": "Sejtek oltása...",
  "OddTip2": "Inkubálás...",
  "OddTip3": "Alanyok feláldozása...",
  "OddTip4": "Bárányok számolása...",
  "OddTip5": "Elhullott szövetek eldobása...",
  "OddTip6": "Őssejtek betakarítása...",
  "OddTip7": "Szerv \"adományok\" gyűjtése...",
  "OddTip8": "Háromfejűek megfigyelése...",
  "OddTip9": "Próbák ismétlése...",
  "OddTip10": "Minták kategorizálása...",
  "OddTip11": "Tipp: Nem harcolhatsz az entrópia ellen."
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/ko_kr/spoilers/spoilers_odd-tips.json
{
    "OddTip1": "세포를 이식하는 중...",
    "OddTip2": "배양중...",
    "OddTip3": "피험자를 희생시키는 중...",
    "OddTip4": "양을 세는중...",
    "OddTip5": "죽은 조직을 폐기하는 중...",
    "OddTip6": "줄기세포를 수확하는 중...",
    "OddTip7": "'기부'된 장기를 수집중...",
    "OddTip8": "머리 세개 달린 괴물을 관찰중...",
    "OddTip9": "실험을 반복하는 중...",
    "OddTip10": "표본을 분류하는 중...",
    "OddTip11": "팁: 엔트로피에는 저항할 수 없습니다."
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/zh_cn/spoilers/odd-tips.json
{
    "OddTip1": "移植细胞...",
    "OddTip2": "孵化中...",
    "OddTip3": "牺牲实验对象...",
    "OddTip4": "数绵羊...",
    "OddTip5": "丢弃死亡组织...",
    "OddTip6": "收获干细胞...",
    "OddTip7": "收集器官'捐赠'...",
    "OddTip8": "观察三头畸形...",
    "OddTip9": "重复试验...",
    "OddTip10": "分类标本...",
    "OddTip11": "提示: 你无法对抗熵。"
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/cs_cz/spoilers/odd-tips.json
{
  "OddTip1": "Roubuji buňky...",
  "OddTip2": "Inkubuji...",
  "OddTip3": "Obětovávám předměty...",
  "OddTip4": "Počítám ovečky...",
  "OddTip5": "Odstraňuji mrtvou tkáň...",
  "OddTip6": "Sklízím kmenové buňky...",
  "OddTip7": "Sbírám \"darované\" orgány...",
  "OddTip8": "Pozoruji tricefal...",
  "OddTip9": "Opakuji zkoušky...",
  "OddTip10": "Rozřazuji vzorky...",
  "OddTip11": "Tip: Nelze bojovat proti entropii."
}

=== FinalForEach/Cosmic-Reach-Localization/assets/base/lang/ja_jp/spoilers/odd-tips.json
{
 "OddTip1": "細胞を移植しています...",
 "OddTip2": "培養中です...",
 "OddTip3": "被験者を犠牲にしています...", 
 "OddTip4": "羊を数えています...",
 "OddTip5": "死亡した組織を廃棄しています...",
 "OddTip6": "幹細胞を収穫しています...",
 "OddTip7": "臓器の「寄付」を収集しています...",
 "OddTip8": "三頭体を観察しています...",
 "OddTip9": "実験を繰り返しています...",
 "OddTip10": "標本を分類しています...",
 "OddTip11": "ヒント: エントロピーには抗えません。" 
}
